### ISSUE TITLE
TypeError: no implicit conversion of nil into String [when using the /feedback form]

### ISSUE THREAD

**Issue by tuxcrafter** [onetimesecret/onetimesecret#148]
```
TypeError: no implicit conversion of nil into String
http://onetimesecret02.bothends.lan:7143/feedback
/etc/onetimesecret/lib/onetime/logic.rb:93:in `escape'
/etc/onetimesecret/lib/onetime/logic.rb:93:in `raise_concerns'
/etc/onetimesecret/lib/onetime/app/web.rb:70:in `block in receive_feedback'
/etc/onetimesecret/lib/onetime/app/web/base.rb:16:in `block in publically'
/etc/onetimesecret/lib/onetime/app/helpers.rb:39:in `carefully'
/etc/onetimesecret/lib/onetime/app/web/base.rb:10:in `publically'
/etc/onetimesecret/lib/onetime/app/web.rb:68:in `receive_feedback'
/etc/onetimesecret/vendor/bundle/ruby/gems/otto-0.4.1/lib/otto.rb:281:in `call'
/etc/onetimesecret/vendor/bundle/ruby/gems/otto-0.4.1/lib/otto.rb:108:in `call'
/etc/onetimesecret/vendor/bundle/ruby/gems/rack-1.4.5/lib/rack/reloader.rb:44:in `call'
/etc/onetimesecret/vendor/bundle/ruby/gems/rack-1.4.5/lib/rack/commonlogger.rb:33:in `call'
/etc/onetimesecret/vendor/bundle/ruby/gems/rack-1.4.5/lib/rack/builder.rb:134:in `call'
/etc/onetimesecret/vendor/bundle/ruby/gems/rack-1.4.5/lib/rack/urlmap.rb:64:in `block in call'
/etc/onetimesecret/vendor/bundle/ruby/gems/rack-1.4.5/lib/rack/urlmap.rb:49:in `each'
/etc/onetimesecret/vendor/bundle/ruby/gems/rack-1.4.5/lib/rack/urlmap.rb:49:in `call'
/etc/onetimesecret/vendor/bundle/ruby/gems/thin-1.5.0/lib/thin/connection.rb:81:in `block in pre_process'
/etc/onetimesecret/vendor/bundle/ruby/gems/thin-1.5.0/lib/thin/connection.rb:79:in `catch'
/etc/onetimesecret/vendor/bundle/ruby/gems/thin-1.5.0/lib/thin/connection.rb:79:in `pre_process'
/etc/onetimesecret/vendor/bundle/ruby/gems/thin-1.5.0/lib/thin/connection.rb:54:in `process'
/etc/onetimesecret/vendor/bundle/ruby/gems/thin-1.5.0/lib/thin/connection.rb:39:in `receive_data'
/etc/onetimesecret/vendor/bundle/ruby/gems/eventmachine-1.2.0.1/lib/eventmachine.rb:194:in `run_machine'
/etc/onetimesecret/vendor/bundle/ruby/gems/eventmachine-1.2.0.1/lib/eventmachine.rb:194:in `run'
/etc/onetimesecret/vendor/bundle/ruby/gems/thin-1.5.0/lib/thin/backends/base.rb:63:in `start'
/etc/onetimesecret/vendor/bundle/ruby/gems/thin-1.5.0/lib/thin/server.rb:159:in `start'
/etc/onetimesecret/vendor/bundle/ruby/gems/thin-1.5.0/lib/thin/controllers/controller.rb:86:in `start'
/etc/onetimesecret/vendor/bundle/ruby/gems/thin-1.5.0/lib/thin/runner.rb:187:in `run_command'
/etc/onetimesecret/vendor/bundle/ruby/gems/thin-1.5.0/lib/thin/runner.rb:152:in `run!'
/etc/onetimesecret/vendor/bundle/ruby/gems/thin-1.5.0/bin/thin:6:in `<top (required)>'
/etc/onetimesecret/vendor/bundle/ruby/bin/thin:23:in `load'
/etc/onetimesecret/vendor/bundle/ruby/bin/thin:23:in `<main>'

```
Are there feedback settings that need to be configured? Where is the feedback sent to?

```
# ruby --version
ruby 2.0.0p648 (2015-12-16) [x86_64-linux]
# redis-cli --version
redis-cli 3.2.12
```

 ```
   "bundle.stdout_lines": [
        "Using addressable 2.2.6",
        "Using highline 1.7.8",
        "Using annoy 0.5.6",
        "Using attic 0.5.3",
        "Using bcrypt 3.1.7",
        "Using bcrypt-ruby 3.1.5",
        "Using crack 0.1.8",
        "Using daemons 1.2.4",
        "Using drydock 0.6.9",
        "Using encryptor 1.1.3",
        "Using eventmachine 1.2.0.1",
        "Using gibbler 0.8.9",
        "Using multi_json 1.12.1",
        "Using redis 2.2.2",
        "Using storable 0.8.9",
        "Using uri-redis 0.4.2",
        "Using familia 0.7.1",
        "Using httparty 0.7.7",
        "Using mime-types 1.25.1",
        "Using polyglot 0.3.5",
        "Using treetop 1.4.15",
        "Using mail 2.5.4",
        "Using mustache 0.99.3",
        "Using rack 1.4.5",
        "Using otto 0.4.1",
        "Using yajl-ruby 1.3.1",
        "Using redis-dump 0.3.2",
        "Using sysinfo 0.7.3",
        "Using thin 1.5.0",
        "Using bundler 1.7.8",
        "Your bundle is complete!",
        "Gems in the group dev were not installed.",
        "It was installed into ./vendor/bundle"
```

**Comment by delano** [comment]
I wasn't able to replicate this but I do remember something like this happening previously. I'd suggest to update to 0.10.1 which you can find here:
https://github.com/onetimesecret/onetimesecret/blob/v0.10.1/

Feedback message are stored in redis DB 11:
https://github.com/onetimesecret/onetimesecret/blob/v0.10.1/lib/onetime/models.rb#L158-L178

See my comment at the bottom of https://github.com/onetimesecret/onetimesecret/issues/164. I give an example of how to interact with a specific redis db.

**Comment by tuxcrafter** [comment]
Thank you Delano for your reply, can you sent a link to the release you want me to test? The blob link is giving a 404.

**Comment by onetimesecret** [comment]
Mia lagunda, my bad. Here you go:
https://github.com/onetimesecret/onetimesecret/releases/tag/v0.10.1
