### ISSUE TITLE
keep getting GET / HTTP/1.1" 401 when logging first time to the app , Oops! You found a bug. Let us know how it happened! page

### ISSUE THREAD

**Issue by meiry** [onetimesecret/onetimesecret#159]
hello 
i installed as was instructed in the README but i keep getting the : Oops! You found a bug. Let us know how it happened! page:
this is how i start it :
```
 bundle exec thin -e dev -R config.ru -p 7143 start
/home/ec2-user/onetimesecret/onetimesecret/lib/onetime/core_ext.rb:30: warning: constant ::Fixnum is deprecated
/usr/share/gems/gems/attic-0.5.3/lib/attic.rb:13: warning: constant ::Fixnum is deprecated
/usr/share/gems/gems/gibbler-0.8.9/lib/gibbler.rb:654: warning: constant ::Fixnum is deprecated
/usr/share/gems/gems/gibbler-0.8.9/lib/gibbler.rb:655: warning: constant ::Bignum is deprecated
2021-04-01 14:38:33 +0000 Thin web server (v1.8.0 codename Possessed Pickle)
2021-04-01 14:38:33 +0000 Maximum connections set to 1024
2021-04-01 14:38:33 +0000 Listening on 0.0.0.0:7143, CTRL+C to stop
E(1617287918):  [:limit, :homepage, "88oij9uyld9inbygnn3j648n9hcl1yt", 5]
undefined method `join' for nil:NilClass
/home/ec2-user/onetimesecret/onetimesecret/lib/onetime/app/helpers.rb:162:in `err'
/home/ec2-user/onetimesecret/onetimesecret/lib/onetime/app/helpers.rb:75:in `rescue in carefully'
/home/ec2-user/onetimesecret/onetimesecret/lib/onetime/app/helpers.rb:41:in `carefully'
/home/ec2-user/onetimesecret/onetimesecret/lib/onetime/app/web/base.rb:10:in `publically'
/home/ec2-user/onetimesecret/onetimesecret/lib/onetime/app/web.rb:14:in `index'
/usr/share/gems/gems/otto-0.4.1/lib/otto.rb:281:in `call'
/usr/share/gems/gems/otto-0.4.1/lib/otto.rb:108:in `call'
/usr/share/gems/gems/rack-2.1.4/lib/rack/reloader.rb:51:in `call'
/usr/share/gems/gems/rack-2.1.4/lib/rack/common_logger.rb:35:in `call'
/usr/share/gems/gems/rack-2.1.4/lib/rack/urlmap.rb:77:in `block in call'
/usr/share/gems/gems/rack-2.1.4/lib/rack/urlmap.rb:61:in `each'
/usr/share/gems/gems/rack-2.1.4/lib/rack/urlmap.rb:61:in `call'
/usr/share/gems/gems/thin-1.8.0/lib/thin/connection.rb:86:in `block in pre_process'
/usr/share/gems/gems/thin-1.8.0/lib/thin/connection.rb:84:in `catch'
/usr/share/gems/gems/thin-1.8.0/lib/thin/connection.rb:84:in `pre_process'
/usr/share/gems/gems/thin-1.8.0/lib/thin/connection.rb:53:in `process'
/usr/share/gems/gems/thin-1.8.0/lib/thin/connection.rb:39:in `receive_data'
/usr/share/gems/gems/eventmachine-1.2.7/lib/eventmachine.rb:195:in `run_machine'
/usr/share/gems/gems/eventmachine-1.2.7/lib/eventmachine.rb:195:in `run'
/usr/share/gems/gems/thin-1.8.0/lib/thin/backends/base.rb:75:in `start'
/usr/share/gems/gems/thin-1.8.0/lib/thin/server.rb:162:in `start'
/usr/share/gems/gems/thin-1.8.0/lib/thin/controllers/controller.rb:87:in `start'
/usr/share/gems/gems/thin-1.8.0/lib/thin/runner.rb:203:in `run_command'
/usr/share/gems/gems/thin-1.8.0/lib/thin/runner.rb:159:in `run!'
/usr/share/gems/gems/thin-1.8.0/bin/thin:6:in `<top (required)>'
/usr/local/bin/thin:23:in `load'
/usr/local/bin/thin:23:in `<top (required)>'
/usr/local/share/gems/gems/bundler-2.2.15/lib/bundler/cli/exec.rb:63:in `load'
/usr/local/share/gems/gems/bundler-2.2.15/lib/bundler/cli/exec.rb:63:in `kernel_load'
/usr/local/share/gems/gems/bundler-2.2.15/lib/bundler/cli/exec.rb:28:in `run'
/usr/local/share/gems/gems/bundler-2.2.15/lib/bundler/cli.rb:494:in `exec'
/usr/local/share/gems/gems/bundler-2.2.15/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
/usr/local/share/gems/gems/bundler-2.2.15/lib/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
/usr/local/share/gems/gems/bundler-2.2.15/lib/bundler/vendor/thor/lib/thor.rb:392:in `dispatch'
/usr/local/share/gems/gems/bundler-2.2.15/lib/bundler/cli.rb:30:in `dispatch'
/usr/local/share/gems/gems/bundler-2.2.15/lib/bundler/vendor/thor/lib/thor/base.rb:485:in `start'
/usr/local/share/gems/gems/bundler-2.2.15/lib/bundler/cli.rb:24:in `start'
/usr/local/share/gems/gems/bundler-2.2.15/exe/bundle:49:in `block in <top (required)>'
/usr/local/share/gems/gems/bundler-2.2.15/lib/bundler/friendly_errors.rb:130:in `with_friendly_errors'
/usr/local/share/gems/gems/bundler-2.2.15/exe/bundle:37:in `<top (required)>'
/usr/local/bin/bundle:23:in `load'
/usr/local/bin/bundle:23:in `<main>'
10.0.255.25 - - [01/Apr/2021:14:38:38 +0000] "GET / HTTP/1.1" 401 - 0.0253
 new static route: /img (/img/favicon.png)
10.0.255.25 - - [01/Apr/2021:14:38:38 +0000] "GET /img/favicon.png HTTP/1.1" 200 189 0.0004
```
and i keep getting this : 

![image](https://user-images.githubusercontent.com/1107316/113311035-8af57000-9311-11eb-81d9-2061d397fec3.png)

**Comment by w3ich3rt** [comment]
I have the same error - can anyone help?

**Comment by maraakate** [comment]
Same here. :(

**Comment by Nikita026** [comment]
I get the same error. can anyone please help?

**Comment by maraakate** [comment]
Downgrading the repo to the last commit from 2018 (before the latest pull request merges) has now allowed the site to work.

**Comment by Nikita026** [comment]
Thanks a lot! This worked for me @maraakate :)

**Comment by meiry** [comment]
i check out  this commit as recomended  :
```
* (HEAD detached at 346a2d3)
```
and then im getting this error :
```
[ec2-user@ip-xx.xx.xx onetimesecret]$ bundle exec thin -e dev -R config.ru -p 7143 start
/usr/share/gems/gems/thin-1.5.0/lib/thin/server.rb:104: warning: constant ::Fixnum is deprecated
/home/ec2-user/onetimesecret/onetimesecret/lib/onetime/core_ext.rb:30: warning: constant ::Fixnum is deprecated
/usr/share/gems/gems/attic-0.5.3/lib/attic.rb:13: warning: constant ::Fixnum is deprecated
/usr/share/gems/gems/gibbler-0.8.9/lib/gibbler.rb:654: warning: constant ::Fixnum is deprecated
/usr/share/gems/gems/gibbler-0.8.9/lib/gibbler.rb:655: warning: constant ::Bignum is deprecated
bundler: failed to load command: thin (/usr/local/bin/thin)
Traceback (most recent call last):
        33: from /usr/local/bin/bundle:23:in `<main>'
        32: from /usr/local/bin/bundle:23:in `load'
        31: from /home/ec2-user/.gem/ruby/gems/bundler-2.2.16/exe/bundle:37:in `<top (required)>'
        30: from /home/ec2-user/.gem/ruby/gems/bundler-2.2.16/lib/bundler/friendly_errors.rb:130:in `with_friendly_errors'
        29: from /home/ec2-user/.gem/ruby/gems/bundler-2.2.16/exe/bundle:49:in `block in <top (required)>'
        28: from /home/ec2-user/.gem/ruby/gems/bundler-2.2.16/lib/bundler/cli.rb:24:in `start'
        27: from /home/ec2-user/.gem/ruby/gems/bundler-2.2.16/lib/bundler/vendor/thor/lib/thor/base.rb:485:in `start'
        26: from /home/ec2-user/.gem/ruby/gems/bundler-2.2.16/lib/bundler/cli.rb:30:in `dispatch'
        25: from /home/ec2-user/.gem/ruby/gems/bundler-2.2.16/lib/bundler/vendor/thor/lib/thor.rb:392:in `dispatch'
        24: from /home/ec2-user/.gem/ruby/gems/bundler-2.2.16/lib/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
        23: from /home/ec2-user/.gem/ruby/gems/bundler-2.2.16/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
        22: from /home/ec2-user/.gem/ruby/gems/bundler-2.2.16/lib/bundler/cli.rb:494:in `exec'
        21: from /home/ec2-user/.gem/ruby/gems/bundler-2.2.16/lib/bundler/cli/exec.rb:28:in `run'
        20: from /home/ec2-user/.gem/ruby/gems/bundler-2.2.16/lib/bundler/cli/exec.rb:63:in `kernel_load'
        19: from /home/ec2-user/.gem/ruby/gems/bundler-2.2.16/lib/bundler/cli/exec.rb:63:in `load'
        18: from /usr/local/bin/thin:23:in `<top (required)>'
        17: from /usr/local/bin/thin:23:in `load'
        16: from /usr/share/gems/gems/thin-1.5.0/bin/thin:6:in `<top (required)>'
        15: from /usr/share/gems/gems/thin-1.5.0/lib/thin/runner.rb:152:in `run!'
        14: from /usr/share/gems/gems/thin-1.5.0/lib/thin/runner.rb:187:in `run_command'
        13: from /usr/share/gems/gems/thin-1.5.0/lib/thin/controllers/controller.rb:71:in `start'
        12: from /usr/share/gems/gems/thin-1.5.0/lib/thin/controllers/controller.rb:181:in `load_rackup_config'
        11: from /usr/share/gems/gems/thin-1.5.0/lib/rack/adapter/loader.rb:33:in `load'
        10: from /usr/share/gems/gems/thin-1.5.0/lib/rack/adapter/loader.rb:33:in `eval'
         9: from config.ru:1:in `<main>'
         8: from config.ru:1:in `new'
         7: from /usr/share/gems/gems/rack-1.4.5/lib/rack/builder.rb:51:in `initialize'
         6: from /usr/share/gems/gems/rack-1.4.5/lib/rack/builder.rb:51:in `instance_eval'
         5: from config.ru:28:in `block in <main>'
         4: from /home/ec2-user/onetimesecret/onetimesecret/lib/onetime.rb:55:in `load!'
         3: from /usr/share/gems/gems/familia-0.7.1/lib/familia.rb:59:in `uri='
         2: from /usr/share/ruby/uri/common.rb:234:in `parse'
         1: from /usr/share/ruby/uri/rfc3986_parser.rb:73:in `parse'
/usr/share/ruby/uri/rfc3986_parser.rb:67:in `split': bad URI(is not URI?): "<%= (ENV['ONETIMESECRET_REDIS_URL'] || 'redis://user:CHANGEME@127.0.0.1:7179/0') + '?timeout=10&thread_safe=false&logging=false' %>" (URI::InvalidURIError)
```

**Comment by maraakate** [comment]
Hi,

I am not in front of the server today; but I will give you more exact instructions on how I was able to make it work over the next day or so.  For what it's worth I am using Ubuntu 18 LTS, I only ran apt-get update/upgrade on it and have denied upgrading to version 20 (or whatever the latest LTS is).  Sorry for the somewhat vague instructions but I come from a mostly Windows environment.

Even after all of this it is not rendering the images properly on the site.  Everything else appears to work, but our email part is not working because it looks like the mailer gem does not support the proper authentication for our Office365 hosted noreply account in our organization.  We do have an SMTP relay for these kinds of situations, but I have not gotten a chance to set it up from our hosted OTS server to make sure that it works.

Otherwise, it DOES work and DOES have 'burn after reading' secrets.

**Comment by delano** [comment]
I'm super late responding to this, sorry.

@maraakate Thanks for stepping in, I appreciated it. There's an upcoming release that includes these fixes, it's just taking us a while to get it over the line.

https://github.com/onetimesecret/onetimesecret/releases/tag/v0.11.0-RC1

**Comment by delano** [comment]
Btw, if you're running from a clone of the git repo, you can make your own local branch:

```bash
$ git fetch 
$ git co -b v0.11.0-RC1 origin/v0.11.0-RC1
```

This was all related to a change between ruby 1.9-2.6 and 2.7 btw. 

@meiry you can open a new ticket for your error message if you please.
