### ISSUE TITLE
Gemfile.lock is outdated

### ISSUE THREAD

**Issue by brotbert** [onetimesecret/onetimesecret#160]
It seems the `Gemfile.lock` hasn't been updated in #157 and breaking a deployment using `BUNDLE_FROZEN` and `BUNDLE_DEPLOYMENT` options to `bundle`:

```
You are trying to install in deployment mode after changing
your Gemfile. Run `bundle install` elsewhere and add the
updated Gemfile.lock to version control.

If this is a development machine, remove the /home/ots/onetimesecret/Gemfile freeze
by running `bundle config unset frozen`.

The dependencies in your gemfile changed

You have added to the Gemfile:
* thin (= 1.8.0)

You have deleted from the Gemfile:
* thin (= 1.5.0)
```

Could you please update the `Gemfile.lock` in the repository?

Thanks!

**Comment by maraakate** [comment]
Bump,

Can we please get this updated?  I'm having a real hard time getting this to run.  Is there any advice on this?  I'm mainly a C programmer and do not have much experience in Ruby, but I am trying to deploy this for use at work.

**Comment by NemesisOfNo** [comment]
I assume this is related to what I'm having with problems with:

`
ots@server:~/onetimesecret$ sudo bundle install --frozen
[sudo] password for ots: 
Traceback (most recent call last):
	1: from /usr/local/bin/bundle:23:in '<main>'
/usr/local/bin/bundle:23:in 'load': cannot load such file -- /usr/share/rubygems-integration/all/gems/bundler-1.16.1/exe/bundle (LoadError)
`

**Comment by jdstone** [comment]
I built the application and run `bundle install` to get the latest `Gemfile.lock`.  I've posted it in a gist [here](https://gist.github.com/jdstone/ba5ce4d4ca7e0242af3af7d07bcffc9c).

**Comment by 116davinder** [comment]
@jdstone thanks for fixing the GemFile but I am seeing other error if I use your updated Gemfile.

```
$ docker run -p 3000:3000 -e ONETIMESECRET_REDIS_URL="redis://172.17.0.1:6379/0" test
2021-05-30 15:56:04 +0000 Thin web server (v1.8.0 codename Possessed Pickle)
2021-05-30 15:56:04 +0000 Maximum connections set to 1024
2021-05-30 15:56:04 +0000 Listening on 0.0.0.0:3000, CTRL+C to stop
undefined method `join' for nil:NilClass
/usr/src/app/lib/onetime/app/helpers.rb:162:in `err'
/usr/src/app/lib/onetime/app/helpers.rb:75:in `rescue in carefully'
/usr/src/app/lib/onetime/app/helpers.rb:83:in `carefully'
/usr/src/app/lib/onetime/app/web/base.rb:10:in `publically'
/usr/src/app/lib/onetime/app/web.rb:14:in `index'
/usr/src/app/vendor/bundle/ruby/2.3.0/gems/otto-0.4.1/lib/otto.rb:281:in `call'
/usr/src/app/vendor/bundle/ruby/2.3.0/gems/otto-0.4.1/lib/otto.rb:108:in `call'
/usr/src/app/vendor/bundle/ruby/2.3.0/gems/rack-2.1.4/lib/rack/urlmap.rb:77:in `block in call'
/usr/src/app/vendor/bundle/ruby/2.3.0/gems/rack-2.1.4/lib/rack/urlmap.rb:61:in `each'
/usr/src/app/vendor/bundle/ruby/2.3.0/gems/rack-2.1.4/lib/rack/urlmap.rb:61:in `call'
/usr/src/app/vendor/bundle/ruby/2.3.0/gems/thin-1.8.0/lib/thin/connection.rb:86:in `block in pre_process'
/usr/src/app/vendor/bundle/ruby/2.3.0/gems/thin-1.8.0/lib/thin/connection.rb:84:in `catch'
/usr/src/app/vendor/bundle/ruby/2.3.0/gems/thin-1.8.0/lib/thin/connection.rb:84:in `pre_process'
/usr/src/app/vendor/bundle/ruby/2.3.0/gems/thin-1.8.0/lib/thin/connection.rb:53:in `process'
/usr/src/app/vendor/bundle/ruby/2.3.0/gems/thin-1.8.0/lib/thin/connection.rb:39:in `receive_data'
/usr/src/app/vendor/bundle/ruby/2.3.0/gems/eventmachine-1.2.7/lib/eventmachine.rb:195:in `run_machine'
/usr/src/app/vendor/bundle/ruby/2.3.0/gems/eventmachine-1.2.7/lib/eventmachine.rb:195:in `run'
/usr/src/app/vendor/bundle/ruby/2.3.0/gems/thin-1.8.0/lib/thin/backends/base.rb:75:in `start'
/usr/src/app/vendor/bundle/ruby/2.3.0/gems/thin-1.8.0/lib/thin/server.rb:162:in `start'
/usr/src/app/vendor/bundle/ruby/2.3.0/gems/thin-1.8.0/lib/thin/controllers/controller.rb:87:in `start'
/usr/src/app/vendor/bundle/ruby/2.3.0/gems/thin-1.8.0/lib/thin/runner.rb:203:in `run_command'
/usr/src/app/vendor/bundle/ruby/2.3.0/gems/thin-1.8.0/lib/thin/runner.rb:159:in `run!'
/usr/src/app/vendor/bundle/ruby/2.3.0/gems/thin-1.8.0/bin/thin:6:in `<top (required)>'
/usr/src/app/vendor/bundle/ruby/2.3.0/bin/thin:23:in `load'
/usr/src/app/vendor/bundle/ruby/2.3.0/bin/thin:23:in `<top (required)>'
/usr/local/lib/ruby/site_ruby/2.3.0/bundler/cli/exec.rb:74:in `load'
/usr/local/lib/ruby/site_ruby/2.3.0/bundler/cli/exec.rb:74:in `kernel_load'
/usr/local/lib/ruby/site_ruby/2.3.0/bundler/cli/exec.rb:28:in `run'
/usr/local/lib/ruby/site_ruby/2.3.0/bundler/cli.rb:463:in `exec'
/usr/local/lib/ruby/site_ruby/2.3.0/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
/usr/local/lib/ruby/site_ruby/2.3.0/bundler/vendor/thor/lib/thor/invocation.rb:126:in `invoke_command'
/usr/local/lib/ruby/site_ruby/2.3.0/bundler/vendor/thor/lib/thor.rb:387:in `dispatch'
/usr/local/lib/ruby/site_ruby/2.3.0/bundler/cli.rb:27:in `dispatch'
/usr/local/lib/ruby/site_ruby/2.3.0/bundler/vendor/thor/lib/thor/base.rb:466:in `start'
/usr/local/lib/ruby/site_ruby/2.3.0/bundler/cli.rb:18:in `start'
/usr/local/bin/bundle:30:in `block in <main>'
/usr/local/lib/ruby/site_ruby/2.3.0/bundler/friendly_errors.rb:124:in `with_friendly_errors'
/usr/local/bin/bundle:22:in `<main>'
 new static route: /css (/css/bootstrap.min.css)
 new static route: /js/vendor (/js/vendor/cufon-yui.js)
 new static route: /js (/js/plugins.js)
 new static route: /img (/img/icon-facebook.png)
```

**Comment by jdstone** [comment]
I got that error as well and although I got the application running, I had all sorts of problems.  I don't know if it's related to the Gemfile.lock file I used or not.

**Comment by gkuhmel** [comment]
hi @jdstone 
the issue is patch here : [https://github.com/onetimesecret/onetimesecret/issues/167](url)
No gemfile.lock related.

**Comment by matiasgarciaisaia** [comment]
If anyone wants to help testing #180, it'll be appreciated.
