### ISSUE TITLE
Docker Hub image?

### ISSUE THREAD

**Issue by FrederikNS** [onetimesecret/onetimesecret#161]
Since we now have an official Dockerfile, would it be possible to also get an official release on Docker Hub?

That way we don't need to build the image ourselves and host it in our own registry, we could simply reference the official image.

**Comment by IbrahimS2** [comment]
I think we need also to set up docker-compose and utilise Traefik proxy to manage and handle all sort of routing as well, in terms of the Dockerfile, it is quite simple and I would rather separate Redis in a separate container, which will focus the main container for the application only.

Any thoughts?

**Comment by tuxpeople** [comment]
Ok, I found this issue, while trying to debug build issues with my own image. My pipeline broke quite a while ago and I didn't had the time to take a look at it.

Cool that you guys have your own Dockerfile. I tried to fix my problems with your Dockerfile, but I failed. I tried to still use mine because I do multiarch builds. I actually also failed to build yours as well:

Current `main` branch:
```
 tdeutsch at odin in /tmp/onetimesecret on main
$ docker build .
[+] Building 20.4s (8/9)
 => [internal] load build definition from Dockerfile                                                                                                                                                                                   0.0s
 => => transferring dockerfile: 1.54kB                                                                                                                                                                                                 0.0s
 => [internal] load .dockerignore                                                                                                                                                                                                      0.0s
 => => transferring context: 94B                                                                                                                                                                                                       0.0s
 => [internal] load metadata for docker.io/library/ruby:2.3                                                                                                                                                                            1.9s
 => [internal] load build context                                                                                                                                                                                                      0.0s
 => => transferring context: 1.56MB                                                                                                                                                                                                    0.0s
 => [1/5] FROM docker.io/library/ruby:2.3@sha256:78cc821d95c48621e577b6b0d44c9d509f0f2a4e089b9fd0ca2ae86f274773a8                                                                                                                     17.8s
 => => resolve docker.io/library/ruby:2.3@sha256:78cc821d95c48621e577b6b0d44c9d509f0f2a4e089b9fd0ca2ae86f274773a8                                                                                                                      0.0s
 => => sha256:79c9f9a430a66c7e307573c8220d0a83a834fdcf4f5034a91730b7015742c75b 2.00kB / 2.00kB                                                                                                                                         0.0s
 => => sha256:e79bb959ec00faf01da52437df4fad4537ec669f60455a38ad583ec2b8f00498 45.34MB / 45.34MB                                                                                                                                       1.6s
 => => sha256:1b2a72d4e03052566e99130108071fc4eca4942c62923e3e5cf19666a23088ef 4.34MB / 4.34MB                                                                                                                                         0.7s
 => => sha256:78cc821d95c48621e577b6b0d44c9d509f0f2a4e089b9fd0ca2ae86f274773a8 2.37kB / 2.37kB                                                                                                                                         0.0s
 => => sha256:c0d23ebb3ed63af928b7c4a954de87a5d3c1fe98a2dfcb2a44e685a3e65c3c61 7.50kB / 7.50kB                                                                                                                                         0.0s
 => => sha256:d4b7902036fe0cefdfe9ccf0404fe13322ecbd552f132be73d3e840f95538838 10.78MB / 10.78MB                                                                                                                                       0.8s
 => => sha256:d54db43011fd116b8cb6d9e49e268cee1fa6212f152b30cbfa7f3c4c684427c3 50.07MB / 50.07MB                                                                                                                                       3.2s
 => => sha256:69d473365bb390367b7a54a3e890ca28c4640a56dfe4f53a0036130c964a1e52 215.05MB / 215.05MB                                                                                                                                     6.4s
 => => sha256:84ed2a0dc034bbdc8a28dfb592e5176338052ada31aa748ce78170876a8a0a84 204B / 204B                                                                                                                                             1.8s
 => => extracting sha256:e79bb959ec00faf01da52437df4fad4537ec669f60455a38ad583ec2b8f00498                                                                                                                                              2.4s
 => => sha256:8952ca0665c56358d62b13871b6a1cb62be5ea173bfa53bfc3a21efa96ca10d8 33.62MB / 33.62MB                                                                                                                                       3.5s
 => => sha256:ef485f36c62492911d22d57cdb485fc295f58e37451fef4a7e8208ca56c36401 149B / 149B                                                                                                                                             3.4s
 => => extracting sha256:d4b7902036fe0cefdfe9ccf0404fe13322ecbd552f132be73d3e840f95538838                                                                                                                                              0.5s
 => => extracting sha256:1b2a72d4e03052566e99130108071fc4eca4942c62923e3e5cf19666a23088ef                                                                                                                                              0.2s
 => => extracting sha256:d54db43011fd116b8cb6d9e49e268cee1fa6212f152b30cbfa7f3c4c684427c3                                                                                                                                              2.3s
 => => extracting sha256:69d473365bb390367b7a54a3e890ca28c4640a56dfe4f53a0036130c964a1e52                                                                                                                                              7.7s
 => => extracting sha256:84ed2a0dc034bbdc8a28dfb592e5176338052ada31aa748ce78170876a8a0a84                                                                                                                                              0.0s
 => => extracting sha256:8952ca0665c56358d62b13871b6a1cb62be5ea173bfa53bfc3a21efa96ca10d8                                                                                                                                              1.5s
 => => extracting sha256:ef485f36c62492911d22d57cdb485fc295f58e37451fef4a7e8208ca56c36401                                                                                                                                              0.0s
 => [2/5] WORKDIR /usr/src/app                                                                                                                                                                                                         0.1s
 => [3/5] COPY Gemfile Gemfile.lock ./                                                                                                                                                                                                 0.0s
 => ERROR [4/5] RUN bundle install --frozen --deployment --without=dev                                                                                                                                                                 0.5s
------
 > [4/5] RUN bundle install --frozen --deployment --without=dev:
#8 0.467 You are trying to install in deployment mode after changing
#8 0.467 your Gemfile. Run `bundle install` elsewhere and add the
#8 0.467 updated Gemfile.lock to version control.
#8 0.467
#8 0.467 The dependencies in your gemfile changed
#8 0.467
#8 0.467 You have added to the Gemfile:
#8 0.467 * thin (= 1.8.0)
#8 0.467
#8 0.467 You have deleted from the Gemfile:
#8 0.467 * thin (= 1.5.0)
------
```

I then switched to to the latest release using `git checkout tags/2021-03-17-0.11.0`. No luck either:
```
 tdeutsch at odin in /tmp/onetimesecret on tags/2021-03-17-0.11.0
$ docker build .
[+] Building 17.7s (8/9)
 => [internal] load build definition from Dockerfile                                                                                                                                                                                   0.0s
 => => transferring dockerfile: 1.54kB                                                                                                                                                                                                 0.0s
 => [internal] load .dockerignore                                                                                                                                                                                                      0.0s
 => => transferring context: 34B                                                                                                                                                                                                       0.0s
 => [internal] load metadata for docker.io/library/ruby:2.6                                                                                                                                                                            1.3s
 => [1/5] FROM docker.io/library/ruby:2.6@sha256:1a19a04ee0c419385a1fcab092f24a884de73a872b0ace73d5c48222dce1580b                                                                                                                     15.9s
 => => resolve docker.io/library/ruby:2.6@sha256:1a19a04ee0c419385a1fcab092f24a884de73a872b0ace73d5c48222dce1580b                                                                                                                      0.0s
 => => sha256:0bc3020d05f1e08b41f1c5d54650a157b1690cde7fedb1fafbc9cda70ee2ec5c 50.44MB / 50.44MB                                                                                                                                       1.3s
 => => sha256:83d3c0fa203acbade733bff627daa75b84c97f9d0553bcdf967a3f1d37471277 10.00MB / 10.00MB                                                                                                                                       1.1s
 => => sha256:1a19a04ee0c419385a1fcab092f24a884de73a872b0ace73d5c48222dce1580b 1.86kB / 1.86kB                                                                                                                                         0.0s
 => => sha256:d0aed6bc1b8cf7ff2de24c5d4450bf1187a5bea05c58eb0a3a79a041cd7342fb 7.23kB / 7.23kB                                                                                                                                         0.0s
 => => sha256:a110e58716600c199fc95f633b30735c33a25b5adcfb16d1d7edbcb78a3f1b62 7.83MB / 7.83MB                                                                                                                                         0.7s
 => => sha256:e306a1a6a8e16bc093327c66950bd4fee7101926e1e1c9ca82733f90d99bfa1b 2.00kB / 2.00kB                                                                                                                                         0.0s
 => => sha256:a8fd09c11b021b756b7a92a4f70a3d444ce7e63a1c24e5749d236dc2c6e68514 51.84MB / 51.84MB                                                                                                                                       3.0s
 => => sha256:14feb89c4a52c44f0a7e23a46ebb76e1c25c4b2915a39656a3ab634c74bcda46 192.39MB / 192.39MB                                                                                                                                     5.3s
 => => sha256:958d2475f1817298c5f46728a3502f7005a641caeaf18d238f1e7befa16bd1da 199B / 199B                                                                                                                                             1.5s
 => => extracting sha256:0bc3020d05f1e08b41f1c5d54650a157b1690cde7fedb1fafbc9cda70ee2ec5c                                                                                                                                              2.9s
 => => sha256:0e4321a8729acd899ae9eb8bbd37a90a9c5cf169d6953b0912ce0993c04f585c 21.50MB / 21.50MB                                                                                                                                       2.5s
 => => sha256:a973a9139e925926e55d592804b25a4dac501d4ac17c961252aac96442fab968 177B / 177B                                                                                                                                             2.7s
 => => extracting sha256:a110e58716600c199fc95f633b30735c33a25b5adcfb16d1d7edbcb78a3f1b62                                                                                                                                              0.4s
 => => extracting sha256:83d3c0fa203acbade733bff627daa75b84c97f9d0553bcdf967a3f1d37471277                                                                                                                                              0.3s
 => => extracting sha256:a8fd09c11b021b756b7a92a4f70a3d444ce7e63a1c24e5749d236dc2c6e68514                                                                                                                                              2.1s
 => => extracting sha256:14feb89c4a52c44f0a7e23a46ebb76e1c25c4b2915a39656a3ab634c74bcda46                                                                                                                                              6.9s
 => => extracting sha256:958d2475f1817298c5f46728a3502f7005a641caeaf18d238f1e7befa16bd1da                                                                                                                                              0.0s
 => => extracting sha256:0e4321a8729acd899ae9eb8bbd37a90a9c5cf169d6953b0912ce0993c04f585c                                                                                                                                              0.5s
 => => extracting sha256:a973a9139e925926e55d592804b25a4dac501d4ac17c961252aac96442fab968                                                                                                                                              0.0s
 => [internal] load build context                                                                                                                                                                                                      0.0s
 => => transferring context: 82.81kB                                                                                                                                                                                                   0.0s
 => [2/5] WORKDIR /usr/src/app                                                                                                                                                                                                         0.1s
 => [3/5] COPY Gemfile Gemfile.lock ./                                                                                                                                                                                                 0.0s
 => ERROR [4/5] RUN bundle install --frozen --deployment --without=dev                                                                                                                                                                 0.3s
------
 > [4/5] RUN bundle install --frozen --deployment --without=dev:
#7 0.261 /usr/local/lib/ruby/2.6.0/rubygems.rb:283:in `find_spec_for_exe': Could not find 'bundler' (2.2.16) required by your /usr/src/app/Gemfile.lock. (Gem::GemNotFoundException)
#7 0.261 To update to the latest version installed on your system, run `bundle update --bundler`.
#7 0.261 To install the missing version, run `gem install bundler:2.2.16`
#7 0.263 	from /usr/local/lib/ruby/2.6.0/rubygems.rb:302:in `activate_bin_path'
#7 0.263 	from /usr/local/bin/bundle:23:in `<main>'
------
executor failed running [/bin/sh -c bundle install --frozen --deployment --without=dev]: exit code: 1
```

I'm more the container guy, not much of a ruby guy. Therefore, I can't fix those problem. What's going wrong here?

@FrederikNS
> Since we now have an official Dockerfile, would it be possible to also get an official release on Docker Hub?
> 
> That way we don't need to build the image ourselves and host it in our own registry, we could simply reference the official image.

To be honest, best way IS to build the images yourself and have it stored in your own registry. As this is the only way to have a trustworthy image. I know, that's probably not what you like to hear. Therefore: If you use docker-compose, you can add `build` to your compose instead instead of the image, it then while build the image for you on the first start. And use the cached build for later starts as long as it's available and the code didn't change.

@IbrahimS2 
> I think we need also to set up docker-compose and utilise Traefik proxy to manage and handle all sort of routing as well, in terms of the Dockerfile, it is quite simple and I would rather separate Redis in a separate container, which will focus the main container for the application only.

Yes please. Redis in a separate container. One container should be one function/app. And you can make use of the official Redis image, if you trust it. Take docker compose, put `onetimesecret` and `redis` in it. Boom. If you do not have yet an reverseproxy and would like to make it available on the internet, maybe together with ssl and other good stuff, also put an `nginx` or `traeffik` in your compose. 

I'm not so sure who is maintaining this repo, based on the recent commits, it's probably @delano. Delano, once the image builds again, would you be interested in a PR containing GitHub actions to build multi arch images and push them to Docker Hub or any other repo (Github Container Registry, Quay.io, whatever) of your choice?

**Comment by delano** [comment]
@tuxpeople Yeah I for sure would. 

I've been going through the dep chain and updating packages as I go. I've been working on a Docker image to run tests with different Ruby versions. The current state of that work is in the storable repo (one of the dependencies):

https://github.com/delano/storable/blob/0.9-RC2/Dockerfile
https://github.com/delano/storable/blob/0.9-RC2/bin/docker-entrypoint.sh
https://github.com/delano/storable/blob/0.9-RC2/Gemfile

It's obviously confusing that updates are split across repos but it's intentional. I want to update this repo towards the end of that work so all the in-progress changes don't leak in here in bits and pieces. So I link to those files as evidence that I'm working on it and maybe that config could help here.

**Comment by tuxpeople** [comment]
@delano let me know once your work approaching the end. I'll then start wo work on the other stuff.

**Comment by delano** [comment]
Roger that

**Comment by davidhaymond** [comment]
I'm also very interested in seeing an official Docker Hub image for this project. Let me know if there's any way I can help.

**Comment by cron410** [comment]
I've got an automated build going for the `develop` branch [here](https://hub.docker.com/r/packetworks/onetimesecret) but had to make some changes to the `dockerfile` and `gemfile` to get it to work. I'm not much of a Ruby guy, so feel free to drop me some insight over at https://github.com/packetworks/onetimesecret

**Comment by delano** [comment]
After recent work on support Ruby 3.2+, the official  images are available on docker hub and github container registry.

https://hub.docker.com/r/onetimesecret/onetimesecret
https://github.com/onetimesecret/onetimesecret/pkgs/container/onetimesecret


(This ticket still gets a lot of search traffic so for updating for posterity.)
