### ISSUE TITLE
bin/ots init failes

### ISSUE THREAD

**Issue by Am0rphous** [onetimesecret/onetimesecret#165]
Hi! By following the procedure we get following error when running the step `bin/ots init`
````bash
Traceback (most recent call last):
	10: from bin/ots:9:in `<main>'
	 9: from /usr/local/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:72:in `require'
	 8: from /usr/local/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:72:in `require'
	 7: from /home/ots/onetimesecret/lib/onetime.rb:13:in `<top (required)>'
	 6: from /home/ots/onetimesecret/lib/onetime.rb:13:in `require'
	 5: from /usr/local/lib/ruby/gems/2.7.0/gems/sysinfo-0.7.3/lib/sysinfo.rb:2:in `<top (required)>'
	 4: from /usr/local/lib/ruby/gems/2.7.0/gems/sysinfo-0.7.3/lib/sysinfo.rb:2:in `require'
	 3: from /usr/local/lib/ruby/gems/2.7.0/gems/storable-0.8.9/lib/storable.rb:33:in `<top (required)>'
	 2: from /usr/local/lib/ruby/gems/2.7.0/gems/storable-0.8.9/lib/storable.rb:35:in `<class:Storable>'
	 1: from /usr/local/lib/ruby/gems/2.7.0/gems/storable-0.8.9/lib/storable.rb:35:in `require'
/usr/local/lib/ruby/gems/2.7.0/gems/storable-0.8.9/lib/proc_source.rb:41:in `<top (required)>': uninitialized constant RubyToken (NameError)
Did you mean?  RubyLex
````
Any thoughts on this?

**Comment by delano** [comment]
Thanks for the report. There's an issue when running with Ruby 2.7 (which we've fixed for the upcoming 0.11 release). For now you should be able to run it with Ruby 2.6.

**Comment by nsoft** [comment]
For those of us that are not ruby devs could you perhaps advise on how best to run with a prior version since the system default on ubuntu 20.04 seems to be 2.7.0?

**Comment by nsoft** [comment]
Attempting to guess my way through this I hit
```
ots@ip-172-30-3-219:~$ rbenv install rbx-2.6
Downloading rubinius-2.6.tar.bz2...
-> https://dqw8nmjcqpjn7.cloudfront.net/f63bbcca7d1bc71b4c20a3bd5748430be001f3a39b14a903d3d4ca39a657cfe0
Installing rubinius-2.6...

WARNING: rubinius-2.6 is past its end of life and is now unsupported.
It no longer receives bug fixes or critical security updates.


BUILD FAILED (Ubuntu 20.04 using ruby-build 20170726)

Inspect or clean up the working tree at /tmp/ruby-build.20210909165020.27208
Results logged to /tmp/ruby-build.20210909165020.27208.log

Last 10 log lines:
Installing aws-sdk-core 2.2.4
Installing rubinius-bridge 1.1.0
Installing rubinius-build_tools 2.0.0
Installing aws-sdk-resources 2.2.4
Installing aws-sdk 2.2.4
Updating files in vendor/cache
Bundle complete! 6 Gemfile dependencies, 15 gems now installed.
Bundled gems are installed into ./vendor/bundle.
/usr/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:92:in `require': cannot load such file -- ubygems (LoadError)
	from /usr/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:92:in `require'

```
