### ISSUE TITLE
Link generation problem

### ISSUE THREAD

**Issue by medipnegiz** [onetimesecret/onetimesecret#252]
**when I enter the password and click on link generation I keep getting the following error. Please help**

```
onetime-app    | E(1682327963):  [:limit, :create_secret, "bo34it8v1fydyye15ic4xy7kxrkadqa", 3]
onetime-app    | onetime[1]: E(1682327963):  [:limit, :create_secret, "bo34it8v1fydyye15ic4xy7kxrkadqa", 3]
onetime-app    | onetime[1]: D(1682327963):  NoMethodError: undefined method `encrypt' for "password: 123456":String
onetime-app    | Did you mean?  crypt
onetime-app    | D(1682327963):  NoMethodError: undefined method `encrypt' for "password: 123456":String
onetime-app    | Did you mean?  crypt
onetime-app    | onetime[1]: D(1682327963):  http://localhost:7143/
onetime-app    | D(1682327963):  http://localhost:7143/
onetime-app    | onetime[1]: D(1682327963):  /app/lib/onetime/models/secret.rb:77:in `encrypt_value'
onetime-app    | /app/lib/onetime/logic.rb:459:in `process'
onetime-app    | /app/lib/onetime/app/web.rb:107:in `block in create_secret'
onetime-app    | /app/lib/onetime/app/web/base.rb:16:in `block in publically'
onetime-app    | /app/lib/onetime/app/helpers.rb:43:in `carefully'
onetime-app    | /app/lib/onetime/app/web/base.rb:10:in `publically'
onetime-app    | /app/lib/onetime/app/web.rb:104:in `create_secret'
onetime-app    | /usr/local/bundle/gems/otto-0.4.1/lib/otto.rb:281:in `call'
onetime-app    | /usr/local/bundle/gems/otto-0.4.1/lib/otto.rb:108:in `call'
onetime-app    | /usr/local/bundle/gems/rack-2.1.4.1/lib/rack/urlmap.rb:77:in `block in call'
onetime-app    | /usr/local/bundle/gems/rack-2.1.4.1/lib/rack/urlmap.rb:61:in `each'
onetime-app    | /usr/local/bundle/gems/rack-2.1.4.1/lib/rack/urlmap.rb:61:in `call'
onetime-app    | /usr/local/bundle/gems/thin-1.8.1/lib/thin/connection.rb:86:in `block in pre_process'
onetime-app    | /usr/local/bundle/gems/thin-1.8.1/lib/thin/connection.rb:84:in `catch'
onetime-app    | /usr/local/bundle/gems/thin-1.8.1/lib/thin/connection.rb:84:in `pre_process'
onetime-app    | /usr/local/bundle/gems/thin-1.8.1/lib/thin/connection.rb:53:in `process'
onetime-app    | /usr/local/bundle/gems/thin-1.8.1/lib/thin/connection.rb:39:in `receive_data'
onetime-app    | /usr/local/bundle/gems/eventmachine-1.2.7/lib/eventmachine.rb:195:in `run_machine'
onetime-app    | /usr/local/bundle/gems/eventmachine-1.2.7/lib/eventmachine.rb:195:in `run'
onetime-app    | /usr/local/bundle/gems/thin-1.8.1/lib/thin/backends/base.rb:75:in `start'
onetime-app    | /usr/local/bundle/gems/thin-1.8.1/lib/thin/server.rb:162:in `start'
onetime-app    | /usr/local/bundle/gems/thin-1.8.1/lib/thin/controllers/controller.rb:87:in `start'
onetime-app    | /usr/local/bundle/gems/thin-1.8.1/lib/thin/runner.rb:203:in `run_command'
onetime-app    | /usr/local/bundle/gems/thin-1.8.1/lib/thin/runner.rb:159:in `run!'
onetime-app    | /usr/local/bundle/gems/thin-1.8.1/bin/thin:6:in `<top (required)>'
onetime-app    | /usr/local/bundle/bin/thin:25:in `load'
onetime-app    | /usr/local/bundle/bin/thin:25:in `<top (required)>'
onetime-app    | /usr/local/bundle/gems/bundler-2.4.12/lib/bundler/cli/exec.rb:58:in `load'
onetime-app    | /usr/local/bundle/gems/bundler-2.4.12/lib/bundler/cli/exec.rb:58:in `kernel_load'
onetime-app    | /usr/local/bundle/gems/bundler-2.4.12/lib/bundler/cli/exec.rb:23:in `run'
onetime-app    | /usr/local/bundle/gems/bundler-2.4.12/lib/bundler/cli.rb:492:in `exec'
onetime-app    | /usr/local/bundle/gems/bundler-2.4.12/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
onetime-app    | /usr/local/bundle/gems/bundler-2.4.12/lib/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
onetime-app    | /usr/local/bundle/gems/bundler-2.4.12/lib/bundler/vendor/thor/lib/thor.rb:392:in `dispatch'
onetime-app    | /usr/local/bundle/gems/bundler-2.4.12/lib/bundler/cli.rb:34:in `dispatch'
onetime-app    | /usr/local/bundle/gems/bundler-2.4.12/lib/bundler/vendor/thor/lib/thor/base.rb:485:in `start'
onetime-app    | /usr/local/bundle/gems/bundler-2.4.12/lib/bundler/cli.rb:28:in `start'
onetime-app    | /usr/local/bundle/gems/bundler-2.4.12/exe/bundle:45:in `block in <top (required)>'
onetime-app    | /usr/local/bundle/gems/bundler-2.4.12/lib/bundler/friendly_errors.rb:117:in `with_friendly_errors'
onetime-app    | /usr/local/bundle/gems/bundler-2.4.12/exe/bundle:33:in `<top (required)>'
onetime-app    | /usr/local/bundle/bin/bundle:25:in `load'
onetime-app    | /usr/local/bundle/bin/bundle:25:in `<top (required)>'
onetime-app    | /usr/local/bundle/gems/bundler-2.4.12/lib/bundler/cli/exec.rb:58:in `load'
onetime-app    | /usr/local/bundle/gems/bundler-2.4.12/lib/bundler/cli/exec.rb:58:in `kernel_load'
onetime-app    | /usr/local/bundle/gems/bundler-2.4.12/lib/bundler/cli/exec.rb:23:in `run'
onetime-app    | /usr/local/bundle/gems/bundler-2.4.12/lib/bundler/cli.rb:492:in `exec'
onetime-app    | /usr/local/bundle/gems/bundler-2.4.12/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
onetime-app    | /usr/local/bundle/gems/bundler-2.4.12/lib/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
onetime-app    | /usr/local/bundle/gems/bundler-2.4.12/lib/bundler/vendor/thor/lib/thor.rb:392:in `dispatch'
onetime-app    | /usr/local/bundle/gems/bundler-2.4.12/lib/bundler/cli.rb:34:in `dispatch'
onetime-app    | /usr/local/bundle/gems/bundler-2.4.12/lib/bundler/vendor/thor/lib/thor/base.rb:485:in `start'
onetime-app    | /usr/local/bundle/gems/bundler-2.4.12/lib/bundler/cli.rb:28:in `start'
onetime-app    | /usr/local/bundle/gems/bundler-2.4.12/exe/bundle:45:in `block in <top (required)>'
onetime-app    | /usr/local/bundle/gems/bundler-2.4.12/lib/bundler/friendly_errors.rb:117:in `with_friendly_errors'
onetime-app    | /usr/local/bundle/gems/bundler-2.4.12/exe/bundle:33:in `<top (required)>'
onetime-app    | /usr/local/bundle/bin/bundle:25:in `load'
onetime-app    | /usr/local/bundle/bin/bundle:25:in `<main>'
onetime-app    | D(1682327963):  /app/lib/onetime/models/secret.rb:77:in `encrypt_value'
onetime-app    | /app/lib/onetime/logic.rb:459:in `process'
onetime-app    | /app/lib/onetime/app/web.rb:107:in `block in create_secret'
onetime-app    | /app/lib/onetime/app/web/base.rb:16:in `block in publically'
onetime-app    | /app/lib/onetime/app/helpers.rb:43:in `carefully'
onetime-app    | /app/lib/onetime/app/web/base.rb:10:in `publically'
onetime-app    | /app/lib/onetime/app/web.rb:104:in `create_secret'
onetime-app    | /usr/local/bundle/gems/otto-0.4.1/lib/otto.rb:281:in `call'
onetime-app    | /usr/local/bundle/gems/otto-0.4.1/lib/otto.rb:108:in `call'
onetime-app    | /usr/local/bundle/gems/rack-2.1.4.1/lib/rack/urlmap.rb:77:in `block in call'
onetime-app    | /usr/local/bundle/gems/rack-2.1.4.1/lib/rack/urlmap.rb:61:in `each'
onetime-app    | /usr/local/bundle/gems/rack-2.1.4.1/lib/rack/urlmap.rb:61:in `call'
onetime-app    | /usr/local/bundle/gems/thin-1.8.1/lib/thin/connection.rb:86:in `block in pre_process'
onetime-app    | /usr/local/bundle/gems/thin-1.8.1/lib/thin/connection.rb:84:in `catch'
onetime-app    | /usr/local/bundle/gems/thin-1.8.1/lib/thin/connection.rb:84:in `pre_process'
onetime-app    | /usr/local/bundle/gems/thin-1.8.1/lib/thin/connection.rb:53:in `process'
onetime-app    | /usr/local/bundle/gems/thin-1.8.1/lib/thin/connection.rb:39:in `receive_data'
onetime-app    | /usr/local/bundle/gems/eventmachine-1.2.7/lib/eventmachine.rb:195:in `run_machine'
onetime-app    | /usr/local/bundle/gems/eventmachine-1.2.7/lib/eventmachine.rb:195:in `run'
onetime-app    | /usr/local/bundle/gems/thin-1.8.1/lib/thin/backends/base.rb:75:in `start'
onetime-app    | /usr/local/bundle/gems/thin-1.8.1/lib/thin/server.rb:162:in `start'
onetime-app    | /usr/local/bundle/gems/thin-1.8.1/lib/thin/controllers/controller.rb:87:in `start'
onetime-app    | /usr/local/bundle/gems/thin-1.8.1/lib/thin/runner.rb:203:in `run_command'
onetime-app    | /usr/local/bundle/gems/thin-1.8.1/lib/thin/runner.rb:159:in `run!'
onetime-app    | /usr/local/bundle/gems/thin-1.8.1/bin/thin:6:in `<top (required)>'
onetime-app    | /usr/local/bundle/bin/thin:25:in `load'
onetime-app    | /usr/local/bundle/bin/thin:25:in `<top (required)>'
onetime-app    | /usr/local/bundle/gems/bundler-2.4.12/lib/bundler/cli/exec.rb:58:in `load'
onetime-app    | /usr/local/bundle/gems/bundler-2.4.12/lib/bundler/cli/exec.rb:58:in `kernel_load'
onetime-app    | /usr/local/bundle/gems/bundler-2.4.12/lib/bundler/cli/exec.rb:23:in `run'
onetime-app    | /usr/local/bundle/gems/bundler-2.4.12/lib/bundler/cli.rb:492:in `exec'
onetime-app    | /usr/local/bundle/gems/bundler-2.4.12/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
onetime-app    | /usr/local/bundle/gems/bundler-2.4.12/lib/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
onetime-app    | /usr/local/bundle/gems/bundler-2.4.12/lib/bundler/vendor/thor/lib/thor.rb:392:in `dispatch'
onetime-app    | /usr/local/bundle/gems/bundler-2.4.12/lib/bundler/cli.rb:34:in `dispatch'
onetime-app    | /usr/local/bundle/gems/bundler-2.4.12/lib/bundler/vendor/thor/lib/thor/base.rb:485:in `start'
onetime-app    | /usr/local/bundle/gems/bundler-2.4.12/lib/bundler/cli.rb:28:in `start'
onetime-app    | /usr/local/bundle/gems/bundler-2.4.12/exe/bundle:45:in `block in <top (required)>'
onetime-app    | /usr/local/bundle/gems/bundler-2.4.12/lib/bundler/friendly_errors.rb:117:in `with_friendly_errors'
onetime-app    | /usr/local/bundle/gems/bundler-2.4.12/exe/bundle:33:in `<top (required)>'
onetime-app    | /usr/local/bundle/bin/bundle:25:in `load'
onetime-app    | /usr/local/bundle/bin/bundle:25:in `<top (required)>'
onetime-app    | /usr/local/bundle/gems/bundler-2.4.12/lib/bundler/cli/exec.rb:58:in `load'
onetime-app    | /usr/local/bundle/gems/bundler-2.4.12/lib/bundler/cli/exec.rb:58:in `kernel_load'
onetime-app    | /usr/local/bundle/gems/bundler-2.4.12/lib/bundler/cli/exec.rb:23:in `run'
onetime-app    | /usr/local/bundle/gems/bundler-2.4.12/lib/bundler/cli.rb:492:in `exec'
onetime-app    | /usr/local/bundle/gems/bundler-2.4.12/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
onetime-app    | /usr/local/bundle/gems/bundler-2.4.12/lib/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
onetime-app    | /usr/local/bundle/gems/bundler-2.4.12/lib/bundler/vendor/thor/lib/thor.rb:392:in `dispatch'
onetime-app    | /usr/local/bundle/gems/bundler-2.4.12/lib/bundler/cli.rb:34:in `dispatch'
onetime-app    | /usr/local/bundle/gems/bundler-2.4.12/lib/bundler/vendor/thor/lib/thor/base.rb:485:in `start'
onetime-app    | /usr/local/bundle/gems/bundler-2.4.12/lib/bundler/cli.rb:28:in `start'
onetime-app    | /usr/local/bundle/gems/bundler-2.4.12/exe/bundle:45:in `block in <top (required)>'
onetime-app    | /usr/local/bundle/gems/bundler-2.4.12/lib/bundler/friendly_errors.rb:117:in `with_friendly_errors'
onetime-app    | /usr/local/bundle/gems/bundler-2.4.12/exe/bundle:33:in `<top (required)>'
onetime-app    | /usr/local/bundle/bin/bundle:25:in `load'
onetime-app    | /usr/local/bundle/bin/bundle:25:in `<main>'
```

**Comment by tmowbray** [comment]
How was this resolved? Have same issue

**Comment by drustan** [comment]
Hello,

I see you closed the issue. I have the same problem. In the end, what was the issue exactly?

**Comment by medipnegiz** [comment]
Hello,
You should set the following variable to false
ONETIMESECRET_SSL="true"

**Comment by drustan** [comment]
Thanks to get back to me so quickly. I just tried what you said, but I still get the same errors :-( I'll try to track this down on my own.

**Comment by sarvsav** [comment]
Hello @drustan , May I request to know if you have solved this issue. I am facing the same error. It's coming for decrypt as well as encrypt function. And, in UI it says, Oops something went wrong.

**Comment by drustan** [comment]
To be honest, I gave up and switched to another tool (Cryptgeon) much simpler to setup.

**Comment by sarvsav** [comment]
Thank you for sharing. It looks really cool and has more features. :)

**Comment by ZakaBel** [comment]
Facing the same issue. Also setting ONETIMESECRET_SSL to false but still getting the same error : 

NoMethodError: undefined method `encrypt' for "XXXXX":String
onetime-app  | Did you mean?  crypt
onetime-app  | D(1690358315):  NoMethodError: undefined method `encrypt' for "XXXXX":String
onetime-app  | Did you mean?  crypt
