### ISSUE TITLE
v0.13.0-RC7: undefined method `register_scheme' for URI:Module (NoMethodError)

### ISSUE THREAD

**Issue by fraenki** [onetimesecret/onetimesecret#334]
While testing 0.13.0-RC7 I've encountered the following error:

Rocky Linux 8.9, Ruby 2.7.8

```
2024-05-15 15:14:54 +0200 Writing PID to /var/run/onetime/ots.pid
bundler: failed to load command: thin (/data/onetimesecret-0.13.0-RC7/vendor/bundle/ruby/2.7.0/bin/thin)
2024-05-15 15:14:54 +0200 Exiting!
/data/onetimesecret-0.13.0-RC7/vendor/bundle/ruby/2.7.0/gems/uri-redis-1.1.2/lib/uri/redis.rb:102:in `<module:URI>': undefined method `register_scheme' for URI:Module (NoMethodError)
	from /data/onetimesecret-0.13.0-RC7/vendor/bundle/ruby/2.7.0/gems/uri-redis-1.1.2/lib/uri/redis.rb:5:in `<top (required)>'
	from /data/onetimesecret-0.13.0-RC7/vendor/bundle/ruby/2.7.0/gems/familia-0.9.3/lib/familia.rb:3:in `require'
	from /data/onetimesecret-0.13.0-RC7/vendor/bundle/ruby/2.7.0/gems/familia-0.9.3/lib/familia.rb:3:in `<top (required)>'
	from /data/onetimesecret-0.13.0-RC7/lib/onetime.rb:16:in `require'
	from /data/onetimesecret-0.13.0-RC7/lib/onetime.rb:16:in `<top (required)>'
	from /data/onetimesecret-0.13.0-RC7/lib/onetime/app/web.rb:2:in `require'
	from /data/onetimesecret-0.13.0-RC7/lib/onetime/app/web.rb:2:in `<top (required)>'
	from config.ru:19:in `require'
	from config.ru:19:in `block in <main>'
	from /data/onetimesecret-0.13.0-RC7/vendor/bundle/ruby/2.7.0/gems/rack-2.2.9/lib/rack/builder.rb:125:in `instance_eval'
	from /data/onetimesecret-0.13.0-RC7/vendor/bundle/ruby/2.7.0/gems/rack-2.2.9/lib/rack/builder.rb:125:in `initialize'
	from config.ru:1:in `new'
	from config.ru:1:in `<main>'
	from /data/onetimesecret-0.13.0-RC7/vendor/bundle/ruby/2.7.0/gems/thin-1.8.2/lib/rack/adapter/loader.rb:33:in `eval'
	from /data/onetimesecret-0.13.0-RC7/vendor/bundle/ruby/2.7.0/gems/thin-1.8.2/lib/rack/adapter/loader.rb:33:in `load'
	from /data/onetimesecret-0.13.0-RC7/vendor/bundle/ruby/2.7.0/gems/thin-1.8.2/lib/thin/controllers/controller.rb:182:in `load_rackup_config'
	from /data/onetimesecret-0.13.0-RC7/vendor/bundle/ruby/2.7.0/gems/thin-1.8.2/lib/thin/controllers/controller.rb:72:in `start'
	from /data/onetimesecret-0.13.0-RC7/vendor/bundle/ruby/2.7.0/gems/thin-1.8.2/lib/thin/runner.rb:203:in `run_command'
	from /data/onetimesecret-0.13.0-RC7/vendor/bundle/ruby/2.7.0/gems/thin-1.8.2/lib/thin/runner.rb:159:in `run!'
	from /data/onetimesecret-0.13.0-RC7/vendor/bundle/ruby/2.7.0/gems/thin-1.8.2/bin/thin:6:in `<top (required)>'
	from /data/onetimesecret-0.13.0-RC7/vendor/bundle/ruby/2.7.0/bin/thin:23:in `load'
	from /data/onetimesecret-0.13.0-RC7/vendor/bundle/ruby/2.7.0/bin/thin:23:in `<top (required)>'
	from /usr/share/gems/gems/bundler-2.2.24/lib/bundler/cli/exec.rb:63:in `load'
	from /usr/share/gems/gems/bundler-2.2.24/lib/bundler/cli/exec.rb:63:in `kernel_load'
	from /usr/share/gems/gems/bundler-2.2.24/lib/bundler/cli/exec.rb:28:in `run'
	from /usr/share/gems/gems/bundler-2.2.24/lib/bundler/cli.rb:475:in `exec'
	from /usr/share/gems/gems/bundler-2.2.24/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
	from /usr/share/gems/gems/bundler-2.2.24/lib/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
	from /usr/share/gems/gems/bundler-2.2.24/lib/bundler/vendor/thor/lib/thor.rb:392:in `dispatch'
	from /usr/share/gems/gems/bundler-2.2.24/lib/bundler/cli.rb:31:in `dispatch'
	from /usr/share/gems/gems/bundler-2.2.24/lib/bundler/vendor/thor/lib/thor/base.rb:485:in `start'
	from /usr/share/gems/gems/bundler-2.2.24/lib/bundler/cli.rb:25:in `start'
	from /usr/share/gems/gems/bundler-2.2.24/libexec/bundle:46:in `block in <top (required)>'
	from /usr/share/gems/gems/bundler-2.2.24/lib/bundler/friendly_errors.rb:128:in `with_friendly_errors'
	from /usr/share/gems/gems/bundler-2.2.24/libexec/bundle:34:in `<top (required)>'
	from /usr/bin/bundle:23:in `load'
	from /usr/bin/bundle:23:in `<main>'
```

**Comment by delano** [comment]
Check your redis connection string in `/etc/config` or if you use environment variables, the value of `REDIS_URL`. Make sure it starts with `redis://`. 

Note that as of RC6, the environment variable names have changed. I just added the warning to the RC7 release notes to make that change more visible. 
https://github.com/onetimesecret/onetimesecret/releases/tag/v0.13.0-RC7

If you were previously running an older release, you much just need to rename `ONETIMESECRET_REDIS_URL` to just `REDIS_URL`.

**Comment by fraenki** [comment]
Thanks, that's most likely the issue.

Could you probably add some error handling for this case? Maybe onetimesecret could verify that _all_ required config options are set, and if one is missing, print a clear error and exit. This would be very useful and would help users to fix similar issues without raising a bug ticket.

**Comment by delano** [comment]
That's a great idea. I added a ticket #335. 

Not sure when I'll schedule that work so in the meantime let me know if anything else comes up.
