### ISSUE TITLE
Unexpected error while processing request: undefined method `custid' for nil

### ISSUE THREAD

**Issue by mavrc** [onetimesecret/onetimesecret#370]
Version: latest, 0.13.0-RC10

I'm just trying to start the app - cloned the current release, copy over a template config and environment and 'podman-compose up' and it starts, however, accessing it in a browser throws an error

The meat: Unexpected error while processing request: undefined method `custid' for nil

Did I just miss some really obvious step? 

Whole log:

```
[app]   | ---  ONETIME app v0.13  -----------------------------------
[app]   | onetime[1]: ---  ONETIME app v0.13  -----------------------------------
[app]   | Sysinfo: ruby-unix-linux-x86_64 (3.3.1)
[app]   | onetime[1]: Sysinfo: ruby-unix-linux-x86_64 (3.3.1)
[app]   | Config: /app/etc/config
[app]   | onetime[1]: Config: /app/etc/config
[app]   | 2024-06-04 02:10:07 +0000 Thin web server (v1.8.2 codename Ruby Razor)
[app]   | 2024-06-04 02:10:07 +0000 Maximum connections set to 1024
[app]   | 2024-06-04 02:10:07 +0000 Listening on 0.0.0.0:3000, CTRL+C to stop
[app]   | onetime[1]: D(1717467041):  TypeError: Unsupported command argument type: NilClass
[app]   | D(1717467041):  TypeError: Unsupported command argument type: NilClass
[app]   | onetime[1]: D(1717467041):  http://localhost:3000/
[app]   | D(1717467041):  http://localhost:3000/
[app]   | onetime[1]: D(1717467041):  /usr/local/bundle/gems/redis-client-0.22.2/lib/redis_client/command_builder.rb:37:in `block in generate'
[app]   | /usr/local/bundle/gems/redis-client-0.22.2/lib/redis_client/command_builder.rb:28:in `map!'
[app]   | /usr/local/bundle/gems/redis-client-0.22.2/lib/redis_client/command_builder.rb:28:in `generate'
[app]   | /usr/local/bundle/gems/redis-client-0.22.2/lib/redis_client.rb:291:in `call_v'
[app]   | /usr/local/bundle/gems/redis-5.2.0/lib/redis/client.rb:90:in `call_v'
[app]   | /usr/local/bundle/gems/redis-5.2.0/lib/redis.rb:152:in `block in send_command'
[app]   | /usr/local/bundle/gems/redis-5.2.0/lib/redis.rb:151:in `synchronize'
[app]   | /usr/local/bundle/gems/redis-5.2.0/lib/redis.rb:151:in `send_command'
[app]   | /usr/local/bundle/gems/redis-5.2.0/lib/redis/commands/hashes.rb:26:in `hset'
[app]   | /usr/local/bundle/gems/familia-0.9.3/lib/familia/redisobject.rb:818:in `[]='
[app]   | /app/lib/onetime/models.rb:141:in `method_missing'
[app]   | /app/lib/onetime/models/session.rb:46:in `create'
[app]   | /app/lib/onetime/app/helpers.rb:135:in `check_session!'
[app]   | /app/lib/onetime/app/web/base.rb:11:in `block in publically'
[app]   | /app/lib/onetime/app/helpers.rb:43:in `carefully'
[app]   | /app/lib/onetime/app/web/base.rb:10:in `publically'
[app]   | /app/lib/onetime/app/web.rb:14:in `index'
[app]   | /usr/local/bundle/gems/otto-1.0.1/lib/otto.rb:281:in `call'
[app]   | /usr/local/bundle/gems/otto-1.0.1/lib/otto.rb:108:in `call'
[app]   | /usr/local/bundle/gems/rack-2.2.9/lib/rack/urlmap.rb:74:in `block in call'
[app]   | /usr/local/bundle/gems/rack-2.2.9/lib/rack/urlmap.rb:58:in `each'
[app]   | /usr/local/bundle/gems/rack-2.2.9/lib/rack/urlmap.rb:58:in `call'
[app]   | /usr/local/bundle/gems/thin-1.8.2/lib/thin/connection.rb:86:in `block in pre_process'
[app]   | /usr/local/bundle/gems/thin-1.8.2/lib/thin/connection.rb:84:in `catch'
[app]   | /usr/local/bundle/gems/thin-1.8.2/lib/thin/connection.rb:84:in `pre_process'
[app]   | /usr/local/bundle/gems/thin-1.8.2/lib/thin/connection.rb:53:in `process'
[app]   | /usr/local/bundle/gems/thin-1.8.2/lib/thin/connection.rb:39:in `receive_data'
[app]   | /usr/local/bundle/gems/eventmachine-1.2.7/lib/eventmachine.rb:195:in `run_machine'
[app]   | /usr/local/bundle/gems/eventmachine-1.2.7/lib/eventmachine.rb:195:in `run'
[app]   | /usr/local/bundle/gems/thin-1.8.2/lib/thin/backends/base.rb:75:in `start'
[app]   | /usr/local/bundle/gems/thin-1.8.2/lib/thin/server.rb:162:in `start'
[app]   | /usr/local/bundle/gems/thin-1.8.2/lib/thin/controllers/controller.rb:87:in `start'
[app]   | /usr/local/bundle/gems/thin-1.8.2/lib/thin/runner.rb:203:in `run_command'
[app]   | /usr/local/bundle/gems/thin-1.8.2/lib/thin/runner.rb:159:in `run!'
[app]   | /usr/local/bundle/gems/thin-1.8.2/bin/thin:6:in `<top (required)>'
[app]   | /usr/local/bundle/bin/thin:25:in `load'
[app]   | /usr/local/bundle/bin/thin:25:in `<top (required)>'
[app]   | /usr/local/bundle/gems/bundler-2.4.12/lib/bundler/cli/exec.rb:58:in `load'
[app]   | /usr/local/bundle/gems/bundler-2.4.12/lib/bundler/cli/exec.rb:58:in `kernel_load'
[app]   | /usr/local/bundle/gems/bundler-2.4.12/lib/bundler/cli/exec.rb:23:in `run'
[app]   | /usr/local/bundle/gems/bundler-2.4.12/lib/bundler/cli.rb:492:in `exec'
[app]   | /usr/local/bundle/gems/bundler-2.4.12/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
[app]   | /usr/local/bundle/gems/bundler-2.4.12/lib/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
[app]   | /usr/local/bundle/gems/bundler-2.4.12/lib/bundler/vendor/thor/lib/thor.rb:392:in `dispatch'
[app]   | /usr/local/bundle/gems/bundler-2.4.12/lib/bundler/cli.rb:34:in `dispatch'
[app]   | /usr/local/bundle/gems/bundler-2.4.12/lib/bundler/vendor/thor/lib/thor/base.rb:485:in `start'
[app]   | /usr/local/bundle/gems/bundler-2.4.12/lib/bundler/cli.rb:28:in `start'
[app]   | /usr/local/bundle/gems/bundler-2.4.12/exe/bundle:45:in `block in <top (required)>'
[app]   | /usr/local/bundle/gems/bundler-2.4.12/lib/bundler/friendly_errors.rb:117:in `with_friendly_errors'
[app]   | /usr/local/bundle/gems/bundler-2.4.12/exe/bundle:33:in `<top (required)>'
[app]   | /usr/local/bundle/bin/bundle:25:in `load'
[app]   | /usr/local/bundle/bin/bundle:25:in `<main>'
[app]   | D(1717467041):  /usr/local/bundle/gems/redis-client-0.22.2/lib/redis_client/command_builder.rb:37:in `block in generate'
[app]   | /usr/local/bundle/gems/redis-client-0.22.2/lib/redis_client/command_builder.rb:28:in `map!'
[app]   | /usr/local/bundle/gems/redis-client-0.22.2/lib/redis_client/command_builder.rb:28:in `generate'
[app]   | /usr/local/bundle/gems/redis-client-0.22.2/lib/redis_client.rb:291:in `call_v'
[app]   | /usr/local/bundle/gems/redis-5.2.0/lib/redis/client.rb:90:in `call_v'
[app]   | /usr/local/bundle/gems/redis-5.2.0/lib/redis.rb:152:in `block in send_command'
[app]   | /usr/local/bundle/gems/redis-5.2.0/lib/redis.rb:151:in `synchronize'
[app]   | /usr/local/bundle/gems/redis-5.2.0/lib/redis.rb:151:in `send_command'
[app]   | /usr/local/bundle/gems/redis-5.2.0/lib/redis/commands/hashes.rb:26:in `hset'
[app]   | /usr/local/bundle/gems/familia-0.9.3/lib/familia/redisobject.rb:818:in `[]='
[app]   | /app/lib/onetime/models.rb:141:in `method_missing'
[app]   | /app/lib/onetime/models/session.rb:46:in `create'
[app]   | /app/lib/onetime/app/helpers.rb:135:in `check_session!'
[app]   | /app/lib/onetime/app/web/base.rb:11:in `block in publically'
[app]   | /app/lib/onetime/app/helpers.rb:43:in `carefully'
[app]   | /app/lib/onetime/app/web/base.rb:10:in `publically'
[app]   | /app/lib/onetime/app/web.rb:14:in `index'
[app]   | /usr/local/bundle/gems/otto-1.0.1/lib/otto.rb:281:in `call'
[app]   | /usr/local/bundle/gems/otto-1.0.1/lib/otto.rb:108:in `call'
[app]   | /usr/local/bundle/gems/rack-2.2.9/lib/rack/urlmap.rb:74:in `block in call'
[app]   | /usr/local/bundle/gems/rack-2.2.9/lib/rack/urlmap.rb:58:in `each'
[app]   | /usr/local/bundle/gems/rack-2.2.9/lib/rack/urlmap.rb:58:in `call'
[app]   | /usr/local/bundle/gems/thin-1.8.2/lib/thin/connection.rb:86:in `block in pre_process'
[app]   | /usr/local/bundle/gems/thin-1.8.2/lib/thin/connection.rb:84:in `catch'
[app]   | /usr/local/bundle/gems/thin-1.8.2/lib/thin/connection.rb:84:in `pre_process'
[app]   | /usr/local/bundle/gems/thin-1.8.2/lib/thin/connection.rb:53:in `process'
[app]   | /usr/local/bundle/gems/thin-1.8.2/lib/thin/connection.rb:39:in `receive_data'
[app]   | /usr/local/bundle/gems/eventmachine-1.2.7/lib/eventmachine.rb:195:in `run_machine'
[app]   | /usr/local/bundle/gems/eventmachine-1.2.7/lib/eventmachine.rb:195:in `run'
[app]   | /usr/local/bundle/gems/thin-1.8.2/lib/thin/backends/base.rb:75:in `start'
[app]   | /usr/local/bundle/gems/thin-1.8.2/lib/thin/server.rb:162:in `start'
[app]   | /usr/local/bundle/gems/thin-1.8.2/lib/thin/controllers/controller.rb:87:in `start'
[app]   | /usr/local/bundle/gems/thin-1.8.2/lib/thin/runner.rb:203:in `run_command'
[app]   | /usr/local/bundle/gems/thin-1.8.2/lib/thin/runner.rb:159:in `run!'
[app]   | /usr/local/bundle/gems/thin-1.8.2/bin/thin:6:in `<top (required)>'
[app]   | /usr/local/bundle/bin/thin:25:in `load'
[app]   | /usr/local/bundle/bin/thin:25:in `<top (required)>'
[app]   | /usr/local/bundle/gems/bundler-2.4.12/lib/bundler/cli/exec.rb:58:in `load'
[app]   | /usr/local/bundle/gems/bundler-2.4.12/lib/bundler/cli/exec.rb:58:in `kernel_load'
[app]   | /usr/local/bundle/gems/bundler-2.4.12/lib/bundler/cli/exec.rb:23:in `run'
[app]   | /usr/local/bundle/gems/bundler-2.4.12/lib/bundler/cli.rb:492:in `exec'
[app]   | /usr/local/bundle/gems/bundler-2.4.12/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
[app]   | /usr/local/bundle/gems/bundler-2.4.12/lib/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
[app]   | /usr/local/bundle/gems/bundler-2.4.12/lib/bundler/vendor/thor/lib/thor.rb:392:in `dispatch'
[app]   | /usr/local/bundle/gems/bundler-2.4.12/lib/bundler/cli.rb:34:in `dispatch'
[app]   | /usr/local/bundle/gems/bundler-2.4.12/lib/bundler/vendor/thor/lib/thor/base.rb:485:in `start'
[app]   | /usr/local/bundle/gems/bundler-2.4.12/lib/bundler/cli.rb:28:in `start'
[app]   | /usr/local/bundle/gems/bundler-2.4.12/exe/bundle:45:in `block in <top (required)>'
[app]   | /usr/local/bundle/gems/bundler-2.4.12/lib/bundler/friendly_errors.rb:117:in `with_friendly_errors'
[app]   | /usr/local/bundle/gems/bundler-2.4.12/exe/bundle:33:in `<top (required)>'
[app]   | /usr/local/bundle/bin/bundle:25:in `load'
[app]   | /usr/local/bundle/bin/bundle:25:in `<main>'
[app]   | undefined method `custid' for nil
[app]   | /app/lib/onetime/app/web/views.rb:49:in `initialize'
[app]   | /app/lib/onetime/app/web/base.rb:87:in `new'
[app]   | /app/lib/onetime/app/web/base.rb:87:in `error_response'
[app]   | /app/lib/onetime/app/helpers.rb:86:in `rescue in carefully'
[app]   | /app/lib/onetime/app/helpers.rb:45:in `carefully'
[app]   | /app/lib/onetime/app/web/base.rb:10:in `publically'
[app]   | /app/lib/onetime/app/web.rb:14:in `index'
[app]   | /usr/local/bundle/gems/otto-1.0.1/lib/otto.rb:281:in `call'
[app]   | /usr/local/bundle/gems/otto-1.0.1/lib/otto.rb:108:in `call'
[app]   | /usr/local/bundle/gems/rack-2.2.9/lib/rack/urlmap.rb:74:in `block in call'
[app]   | /usr/local/bundle/gems/rack-2.2.9/lib/rack/urlmap.rb:58:in `each'
[app]   | /usr/local/bundle/gems/rack-2.2.9/lib/rack/urlmap.rb:58:in `call'
[app]   | /usr/local/bundle/gems/thin-1.8.2/lib/thin/connection.rb:86:in `block in pre_process'
[app]   | /usr/local/bundle/gems/thin-1.8.2/lib/thin/connection.rb:84:in `catch'
[app]   | /usr/local/bundle/gems/thin-1.8.2/lib/thin/connection.rb:84:in `pre_process'
[app]   | /usr/local/bundle/gems/thin-1.8.2/lib/thin/connection.rb:53:in `process'
[app]   | /usr/local/bundle/gems/thin-1.8.2/lib/thin/connection.rb:39:in `receive_data'
[app]   | /usr/local/bundle/gems/eventmachine-1.2.7/lib/eventmachine.rb:195:in `run_machine'
[app]   | /usr/local/bundle/gems/eventmachine-1.2.7/lib/eventmachine.rb:195:in `run'
[app]   | /usr/local/bundle/gems/thin-1.8.2/lib/thin/backends/base.rb:75:in `start'
[app]   | /usr/local/bundle/gems/thin-1.8.2/lib/thin/server.rb:162:in `start'
[app]   | /usr/local/bundle/gems/thin-1.8.2/lib/thin/controllers/controller.rb:87:in `start'
[app]   | /usr/local/bundle/gems/thin-1.8.2/lib/thin/runner.rb:203:in `run_command'
[app]   | /usr/local/bundle/gems/thin-1.8.2/lib/thin/runner.rb:159:in `run!'
[app]   | /usr/local/bundle/gems/thin-1.8.2/bin/thin:6:in `<top (required)>'
[app]   | /usr/local/bundle/bin/thin:25:in `load'
[app]   | /usr/local/bundle/bin/thin:25:in `<top (required)>'
[app]   | /usr/local/bundle/gems/bundler-2.4.12/lib/bundler/cli/exec.rb:58:in `load'
[app]   | /usr/local/bundle/gems/bundler-2.4.12/lib/bundler/cli/exec.rb:58:in `kernel_load'
[app]   | /usr/local/bundle/gems/bundler-2.4.12/lib/bundler/cli/exec.rb:23:in `run'
[app]   | /usr/local/bundle/gems/bundler-2.4.12/lib/bundler/cli.rb:492:in `exec'
[app]   | /usr/local/bundle/gems/bundler-2.4.12/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
[app]   | /usr/local/bundle/gems/bundler-2.4.12/lib/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
[app]   | /usr/local/bundle/gems/bundler-2.4.12/lib/bundler/vendor/thor/lib/thor.rb:392:in `dispatch'
[app]   | /usr/local/bundle/gems/bundler-2.4.12/lib/bundler/cli.rb:34:in `dispatch'
[app]   | /usr/local/bundle/gems/bundler-2.4.12/lib/bundler/vendor/thor/lib/thor/base.rb:485:in `start'
[app]   | /usr/local/bundle/gems/bundler-2.4.12/lib/bundler/cli.rb:28:in `start'
[app]   | /usr/local/bundle/gems/bundler-2.4.12/exe/bundle:45:in `block in <top (required)>'
[app]   | /usr/local/bundle/gems/bundler-2.4.12/lib/bundler/friendly_errors.rb:117:in `with_friendly_errors'
[app]   | /usr/local/bundle/gems/bundler-2.4.12/exe/bundle:33:in `<top (required)>'
[app]   | /usr/local/bundle/bin/bundle:25:in `load'
[app]   | /usr/local/bundle/bin/bundle:25:in `<main>'
[app]   | onetime[1]: D(1717467041):  TypeError: Unsupported command argument type: NilClass
[app]   | D(1717467041):  TypeError: Unsupported command argument type: NilClass
[app]   | onetime[1]: D(1717467041):  http://localhost:3000/
[app]   | D(1717467041):  http://localhost:3000/
[app]   | onetime[1]: D(1717467041):  /usr/local/bundle/gems/redis-client-0.22.2/lib/redis_client/command_builder.rb:37:in `block in generate'
[app]   | /usr/local/bundle/gems/redis-client-0.22.2/lib/redis_client/command_builder.rb:28:in `map!'
[app]   | /usr/local/bundle/gems/redis-client-0.22.2/lib/redis_client/command_builder.rb:28:in `generate'
[app]   | /usr/local/bundle/gems/redis-client-0.22.2/lib/redis_client.rb:291:in `call_v'
[app]   | /usr/local/bundle/gems/redis-5.2.0/lib/redis/client.rb:90:in `call_v'
[app]   | /usr/local/bundle/gems/redis-5.2.0/lib/redis.rb:152:in `block in send_command'
[app]   | /usr/local/bundle/gems/redis-5.2.0/lib/redis.rb:151:in `synchronize'
[app]   | /usr/local/bundle/gems/redis-5.2.0/lib/redis.rb:151:in `send_command'
[app]   | /usr/local/bundle/gems/redis-5.2.0/lib/redis/commands/hashes.rb:26:in `hset'
[app]   | /usr/local/bundle/gems/familia-0.9.3/lib/familia/redisobject.rb:818:in `[]='
[app]   | /app/lib/onetime/models.rb:141:in `method_missing'
[app]   | /app/lib/onetime/models/session.rb:46:in `create'
[app]   | /app/lib/onetime/app/helpers.rb:135:in `check_session!'
[app]   | /app/lib/onetime/app/web/base.rb:11:in `block in publically'
[app]   | /app/lib/onetime/app/helpers.rb:43:in `carefully'
[app]   | /app/lib/onetime/app/web/base.rb:10:in `publically'
[app]   | /app/lib/onetime/app/web/base.rb:74:in `server_error'
[app]   | /usr/local/bundle/gems/otto-1.0.1/lib/otto.rb:281:in `call'
[app]   | /usr/local/bundle/gems/otto-1.0.1/lib/otto.rb:156:in `rescue in call'
[app]   | /usr/local/bundle/gems/otto-1.0.1/lib/otto.rb:87:in `call'
[app]   | /usr/local/bundle/gems/rack-2.2.9/lib/rack/urlmap.rb:74:in `block in call'
[app]   | /usr/local/bundle/gems/rack-2.2.9/lib/rack/urlmap.rb:58:in `each'
[app]   | /usr/local/bundle/gems/rack-2.2.9/lib/rack/urlmap.rb:58:in `call'
[app]   | /usr/local/bundle/gems/thin-1.8.2/lib/thin/connection.rb:86:in `block in pre_process'
[app]   | /usr/local/bundle/gems/thin-1.8.2/lib/thin/connection.rb:84:in `catch'
[app]   | /usr/local/bundle/gems/thin-1.8.2/lib/thin/connection.rb:84:in `pre_process'
[app]   | /usr/local/bundle/gems/thin-1.8.2/lib/thin/connection.rb:53:in `process'
[app]   | /usr/local/bundle/gems/thin-1.8.2/lib/thin/connection.rb:39:in `receive_data'
[app]   | /usr/local/bundle/gems/eventmachine-1.2.7/lib/eventmachine.rb:195:in `run_machine'
[app]   | /usr/local/bundle/gems/eventmachine-1.2.7/lib/eventmachine.rb:195:in `run'
[app]   | /usr/local/bundle/gems/thin-1.8.2/lib/thin/backends/base.rb:75:in `start'
[app]   | /usr/local/bundle/gems/thin-1.8.2/lib/thin/server.rb:162:in `start'
[app]   | /usr/local/bundle/gems/thin-1.8.2/lib/thin/controllers/controller.rb:87:in `start'
[app]   | /usr/local/bundle/gems/thin-1.8.2/lib/thin/runner.rb:203:in `run_command'
[app]   | /usr/local/bundle/gems/thin-1.8.2/lib/thin/runner.rb:159:in `run!'
[app]   | /usr/local/bundle/gems/thin-1.8.2/bin/thin:6:in `<top (required)>'
[app]   | /usr/local/bundle/bin/thin:25:in `load'
[app]   | /usr/local/bundle/bin/thin:25:in `<top (required)>'
[app]   | /usr/local/bundle/gems/bundler-2.4.12/lib/bundler/cli/exec.rb:58:in `load'
[app]   | /usr/local/bundle/gems/bundler-2.4.12/lib/bundler/cli/exec.rb:58:in `kernel_load'
[app]   | /usr/local/bundle/gems/bundler-2.4.12/lib/bundler/cli/exec.rb:23:in `run'
[app]   | /usr/local/bundle/gems/bundler-2.4.12/lib/bundler/cli.rb:492:in `exec'
[app]   | /usr/local/bundle/gems/bundler-2.4.12/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
[app]   | /usr/local/bundle/gems/bundler-2.4.12/lib/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
[app]   | /usr/local/bundle/gems/bundler-2.4.12/lib/bundler/vendor/thor/lib/thor.rb:392:in `dispatch'
[app]   | /usr/local/bundle/gems/bundler-2.4.12/lib/bundler/cli.rb:34:in `dispatch'
[app]   | /usr/local/bundle/gems/bundler-2.4.12/lib/bundler/vendor/thor/lib/thor/base.rb:485:in `start'
[app]   | /usr/local/bundle/gems/bundler-2.4.12/lib/bundler/cli.rb:28:in `start'
[app]   | /usr/local/bundle/gems/bundler-2.4.12/exe/bundle:45:in `block in <top (required)>'
[app]   | /usr/local/bundle/gems/bundler-2.4.12/lib/bundler/friendly_errors.rb:117:in `with_friendly_errors'
[app]   | /usr/local/bundle/gems/bundler-2.4.12/exe/bundle:33:in `<top (required)>'
[app]   | /usr/local/bundle/bin/bundle:25:in `load'
[app]   | /usr/local/bundle/bin/bundle:25:in `<main>'
[app]   | D(1717467041):  /usr/local/bundle/gems/redis-client-0.22.2/lib/redis_client/command_builder.rb:37:in `block in generate'
[app]   | /usr/local/bundle/gems/redis-client-0.22.2/lib/redis_client/command_builder.rb:28:in `map!'
[app]   | /usr/local/bundle/gems/redis-client-0.22.2/lib/redis_client/command_builder.rb:28:in `generate'
[app]   | /usr/local/bundle/gems/redis-client-0.22.2/lib/redis_client.rb:291:in `call_v'
[app]   | /usr/local/bundle/gems/redis-5.2.0/lib/redis/client.rb:90:in `call_v'
[app]   | /usr/local/bundle/gems/redis-5.2.0/lib/redis.rb:152:in `block in send_command'
[app]   | /usr/local/bundle/gems/redis-5.2.0/lib/redis.rb:151:in `synchronize'
[app]   | /usr/local/bundle/gems/redis-5.2.0/lib/redis.rb:151:in `send_command'
[app]   | /usr/local/bundle/gems/redis-5.2.0/lib/redis/commands/hashes.rb:26:in `hset'
[app]   | /usr/local/bundle/gems/familia-0.9.3/lib/familia/redisobject.rb:818:in `[]='
[app]   | /app/lib/onetime/models.rb:141:in `method_missing'
[app]   | /app/lib/onetime/models/session.rb:46:in `create'
[app]   | /app/lib/onetime/app/helpers.rb:135:in `check_session!'
[app]   | /app/lib/onetime/app/web/base.rb:11:in `block in publically'
[app]   | /app/lib/onetime/app/helpers.rb:43:in `carefully'
[app]   | /app/lib/onetime/app/web/base.rb:10:in `publically'
[app]   | /app/lib/onetime/app/web/base.rb:74:in `server_error'
[app]   | /usr/local/bundle/gems/otto-1.0.1/lib/otto.rb:281:in `call'
[app]   | /usr/local/bundle/gems/otto-1.0.1/lib/otto.rb:156:in `rescue in call'
[app]   | /usr/local/bundle/gems/otto-1.0.1/lib/otto.rb:87:in `call'
[app]   | /usr/local/bundle/gems/rack-2.2.9/lib/rack/urlmap.rb:74:in `block in call'
[app]   | /usr/local/bundle/gems/rack-2.2.9/lib/rack/urlmap.rb:58:in `each'
[app]   | /usr/local/bundle/gems/rack-2.2.9/lib/rack/urlmap.rb:58:in `call'
[app]   | /usr/local/bundle/gems/thin-1.8.2/lib/thin/connection.rb:86:in `block in pre_process'
[app]   | /usr/local/bundle/gems/thin-1.8.2/lib/thin/connection.rb:84:in `catch'
[app]   | /usr/local/bundle/gems/thin-1.8.2/lib/thin/connection.rb:84:in `pre_process'
[app]   | /usr/local/bundle/gems/thin-1.8.2/lib/thin/connection.rb:53:in `process'
[app]   | /usr/local/bundle/gems/thin-1.8.2/lib/thin/connection.rb:39:in `receive_data'
[app]   | /usr/local/bundle/gems/eventmachine-1.2.7/lib/eventmachine.rb:195:in `run_machine'
[app]   | /usr/local/bundle/gems/eventmachine-1.2.7/lib/eventmachine.rb:195:in `run'
[app]   | /usr/local/bundle/gems/thin-1.8.2/lib/thin/backends/base.rb:75:in `start'
[app]   | /usr/local/bundle/gems/thin-1.8.2/lib/thin/server.rb:162:in `start'
[app]   | /usr/local/bundle/gems/thin-1.8.2/lib/thin/controllers/controller.rb:87:in `start'
[app]   | /usr/local/bundle/gems/thin-1.8.2/lib/thin/runner.rb:203:in `run_command'
[app]   | /usr/local/bundle/gems/thin-1.8.2/lib/thin/runner.rb:159:in `run!'
[app]   | /usr/local/bundle/gems/thin-1.8.2/bin/thin:6:in `<top (required)>'
[app]   | /usr/local/bundle/bin/thin:25:in `load'
[app]   | /usr/local/bundle/bin/thin:25:in `<top (required)>'
[app]   | /usr/local/bundle/gems/bundler-2.4.12/lib/bundler/cli/exec.rb:58:in `load'
[app]   | /usr/local/bundle/gems/bundler-2.4.12/lib/bundler/cli/exec.rb:58:in `kernel_load'
[app]   | /usr/local/bundle/gems/bundler-2.4.12/lib/bundler/cli/exec.rb:23:in `run'
[app]   | /usr/local/bundle/gems/bundler-2.4.12/lib/bundler/cli.rb:492:in `exec'
[app]   | /usr/local/bundle/gems/bundler-2.4.12/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
[app]   | /usr/local/bundle/gems/bundler-2.4.12/lib/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
[app]   | /usr/local/bundle/gems/bundler-2.4.12/lib/bundler/vendor/thor/lib/thor.rb:392:in `dispatch'
[app]   | /usr/local/bundle/gems/bundler-2.4.12/lib/bundler/cli.rb:34:in `dispatch'
[app]   | /usr/local/bundle/gems/bundler-2.4.12/lib/bundler/vendor/thor/lib/thor/base.rb:485:in `start'
[app]   | /usr/local/bundle/gems/bundler-2.4.12/lib/bundler/cli.rb:28:in `start'
[app]   | /usr/local/bundle/gems/bundler-2.4.12/exe/bundle:45:in `block in <top (required)>'
[app]   | /usr/local/bundle/gems/bundler-2.4.12/lib/bundler/friendly_errors.rb:117:in `with_friendly_errors'
[app]   | /usr/local/bundle/gems/bundler-2.4.12/exe/bundle:33:in `<top (required)>'
[app]   | /usr/local/bundle/bin/bundle:25:in `load'
[app]   | /usr/local/bundle/bin/bundle:25:in `<main>'
[app]   | 2024-06-04 02:10:41 +0000 Unexpected error while processing request: undefined method `custid' for nil
[app]   |       /app/lib/onetime/app/web/views.rb:49:in `initialize'
[app]   |       /app/lib/onetime/app/web/base.rb:87:in `new'
[app]   |       /app/lib/onetime/app/web/base.rb:87:in `error_response'
[app]   |       /app/lib/onetime/app/helpers.rb:86:in `rescue in carefully'
[app]   |       /app/lib/onetime/app/helpers.rb:45:in `carefully'
[app]   |       /app/lib/onetime/app/web/base.rb:10:in `publically'
[app]   |       /app/lib/onetime/app/web/base.rb:74:in `server_error'
[app]   |       /usr/local/bundle/gems/otto-1.0.1/lib/otto.rb:281:in `call'
[app]   |       /usr/local/bundle/gems/otto-1.0.1/lib/otto.rb:156:in `rescue in call'
[app]   |       /usr/local/bundle/gems/otto-1.0.1/lib/otto.rb:87:in `call'
[app]   |       /usr/local/bundle/gems/rack-2.2.9/lib/rack/urlmap.rb:74:in `block in call'
[app]   |       /usr/local/bundle/gems/rack-2.2.9/lib/rack/urlmap.rb:58:in `each'
[app]   |       /usr/local/bundle/gems/rack-2.2.9/lib/rack/urlmap.rb:58:in `call'
[app]   |       /usr/local/bundle/gems/thin-1.8.2/lib/thin/connection.rb:86:in `block in pre_process'
[app]   |       /usr/local/bundle/gems/thin-1.8.2/lib/thin/connection.rb:84:in `catch'
[app]   |       /usr/local/bundle/gems/thin-1.8.2/lib/thin/connection.rb:84:in `pre_process'
[app]   |       /usr/local/bundle/gems/thin-1.8.2/lib/thin/connection.rb:53:in `process'
[app]   |       /usr/local/bundle/gems/thin-1.8.2/lib/thin/connection.rb:39:in `receive_data'
[app]   |       /usr/local/bundle/gems/eventmachine-1.2.7/lib/eventmachine.rb:195:in `run_machine'
[app]   |       /usr/local/bundle/gems/eventmachine-1.2.7/lib/eventmachine.rb:195:in `run'
[app]   |       /usr/local/bundle/gems/thin-1.8.2/lib/thin/backends/base.rb:75:in `start'
[app]   |       /usr/local/bundle/gems/thin-1.8.2/lib/thin/server.rb:162:in `start'
[app]   |       /usr/local/bundle/gems/thin-1.8.2/lib/thin/controllers/controller.rb:87:in `start'
[app]   |       /usr/local/bundle/gems/thin-1.8.2/lib/thin/runner.rb:203:in `run_command'
[app]   |       /usr/local/bundle/gems/thin-1.8.2/lib/thin/runner.rb:159:in `run!'
[app]   |       /usr/local/bundle/gems/thin-1.8.2/bin/thin:6:in `<top (required)>'
[app]   |       /usr/local/bundle/bin/thin:25:in `load'
[app]   |       /usr/local/bundle/bin/thin:25:in `<top (required)>'
[app]   |       /usr/local/bundle/gems/bundler-2.4.12/lib/bundler/cli/exec.rb:58:in `load'
[app]   |       /usr/local/bundle/gems/bundler-2.4.12/lib/bundler/cli/exec.rb:58:in `kernel_load'
[app]   |       /usr/local/bundle/gems/bundler-2.4.12/lib/bundler/cli/exec.rb:23:in `run'
[app]   |       /usr/local/bundle/gems/bundler-2.4.12/lib/bundler/cli.rb:492:in `exec'
[app]   |       /usr/local/bundle/gems/bundler-2.4.12/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
[app]   |       /usr/local/bundle/gems/bundler-2.4.12/lib/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
[app]   |       /usr/local/bundle/gems/bundler-2.4.12/lib/bundler/vendor/thor/lib/thor.rb:392:in `dispatch'
[app]   |       /usr/local/bundle/gems/bundler-2.4.12/lib/bundler/cli.rb:34:in `dispatch'
[app]   |       /usr/local/bundle/gems/bundler-2.4.12/lib/bundler/vendor/thor/lib/thor/base.rb:485:in `start'
[app]   |       /usr/local/bundle/gems/bundler-2.4.12/lib/bundler/cli.rb:28:in `start'
[app]   |       /usr/local/bundle/gems/bundler-2.4.12/exe/bundle:45:in `block in <top (required)>'
[app]   |       /usr/local/bundle/gems/bundler-2.4.12/lib/bundler/friendly_errors.rb:117:in `with_friendly_errors'
[app]   |       /usr/local/bundle/gems/bundler-2.4.12/exe/bundle:33:in `<top (required)>'
[app]   |       /usr/local/bundle/bin/bundle:25:in `load'
[app]   |       /usr/local/bundle/bin/bundle:25:in `<main>'
[app]   | 
[app]   |  new static route: /favicon.ico (/favicon.ico)

```

**Comment by MirRad** [comment]
Same issue here. New install. .env, etc/config and etc/redis.conf properly configured. In the browser I get "Internal server error" and same cli error as in the post from @mavrc

**Comment by ducna96** [comment]
same issue here, i just change CHANGEME at .env, etc/config and get error

**Comment by delano** [comment]
Thanks fir the report and confirmations. It looks like it's related to upgrading the redis client from 4.8 to 5.0.

I've reverted that change and updated `develop`. I'll push RC-11 now and create a ticket to investigate further (and write a regression test).

**Comment by MirRad** [comment]
RC11 solved my issue, thanks @delano
