### ISSUE TITLE
bundler: failed to load command: thin

### ISSUE THREAD

**Issue by mitrasero** [onetimesecret/onetimesecret#55]
Hi
i try to run bundle exec thin -e dev -R config.ru -p 7143 start
but it fails to load ...
i got:
bundler: failed to load command: thin (/home/ots/onetimesecret/vendor/bundle/ruby/1.9.1/bin/thin)
RuntimeError: ERR Client sent AUTH, but no password is set

on /etc/onetime/config ive changed the passwords but still not working.
would appreciate any assistance

ots@ip-10-210-9-109:~/onetimesecret$ cat /etc/onetime/config | egrep -i "key|change|pass"
NOTE Once the secret is set, do not change it (keep a backup offsite)

CHANGEME@EXAMPLE.com
:account: CHANGEME
:password: mynewpassword
:from: CHANGEME@example.com
:fromname: CHANGEME
:pass:
link is sent. Passphrase is used to protect the secret.
:passphrase: mynewpassword
:apikey: mynewpassword
:default_chart: CHANGEME
:failed_passphrase: 5
ots@ip-10-210-9-109:~/onetimesecret$ bundle exec thin -e dev -R config.ru -p 7143 start
bundler: failed to load command: thin (/home/ots/onetimesecret/vendor/bundle/ruby/1.9.1/bin/thin)
RuntimeError: ERR Client sent AUTH, but no password is set
/home/ots/onetimesecret/vendor/bundle/ruby/1.9.1/gems/redis-2.2.2/lib/redis/client.rb:47:in call' /home/ots/onetimesecret/vendor/bundle/ruby/1.9.1/gems/redis-2.2.2/lib/redis/client.rb:24:inconnect'
/home/ots/onetimesecret/vendor/bundle/ruby/1.9.1/gems/redis-2.2.2/lib/redis/client.rb:247:in ensure_connected' /home/ots/onetimesecret/vendor/bundle/ruby/1.9.1/gems/redis-2.2.2/lib/redis/client.rb:137:inblock in process'
/home/ots/onetimesecret/vendor/bundle/ruby/1.9.1/gems/redis-2.2.2/lib/redis/client.rb:206:in logging' /home/ots/onetimesecret/vendor/bundle/ruby/1.9.1/gems/redis-2.2.2/lib/redis/client.rb:136:inprocess'
/home/ots/onetimesecret/vendor/bundle/ruby/1.9.1/gems/redis-2.2.2/lib/redis/client.rb:46:in call' /home/ots/onetimesecret/vendor/bundle/ruby/1.9.1/gems/redis-2.2.2/lib/redis.rb:273:inblock in ping'
/home/ots/onetimesecret/vendor/bundle/ruby/1.9.1/gems/redis-2.2.2/lib/redis.rb:18:in synchronize' /home/ots/onetimesecret/vendor/bundle/ruby/1.9.1/gems/redis-2.2.2/lib/redis.rb:272:inping'
/home/ots/onetimesecret/lib/onetime.rb:73:in block in load!' /home/ots/onetimesecret/lib/onetime.rb:73:intimes'
/home/ots/onetimesecret/lib/onetime.rb:73:in load!' config.ru:28:inblock in

'
/home/ots/onetimesecret/vendor/bundle/ruby/1.9.1/gems/rack-1.4.5/lib/rack/builder.rb:51:in instance_eval' /home/ots/onetimesecret/vendor/bundle/ruby/1.9.1/gems/rack-1.4.5/lib/rack/builder.rb:51:ininitialize'
config.ru:1:in new' config.ru:1:in'
/home/ots/onetimesecret/vendor/bundle/ruby/1.9.1/gems/thin-1.5.0/lib/rack/adapter/loader.rb:33:in eval' /home/ots/onetimesecret/vendor/bundle/ruby/1.9.1/gems/thin-1.5.0/lib/rack/adapter/loader.rb:33:inload'
/home/ots/onetimesecret/vendor/bundle/ruby/1.9.1/gems/thin-1.5.0/lib/thin/controllers/controller.rb:181:in load_rackup_config' /home/ots/onetimesecret/vendor/bundle/ruby/1.9.1/gems/thin-1.5.0/lib/thin/controllers/controller.rb:71:instart'
/home/ots/onetimesecret/vendor/bundle/ruby/1.9.1/gems/thin-1.5.0/lib/thin/runner.rb:187:in run_command' /home/ots/onetimesecret/vendor/bundle/ruby/1.9.1/gems/thin-1.5.0/lib/thin/runner.rb:152:inrun!'
/home/ots/onetimesecret/vendor/bundle/ruby/1.9.1/gems/thin-1.5.0/bin/thin:6:in <top (required)>' /home/ots/onetimesecret/vendor/bundle/ruby/1.9.1/bin/thin:23:inload'
/home/ots/onetimesecret/vendor/bundle/ruby/1.9.1/bin/thin:23:in `<top (required)>'

**Comment by delano** [comment]
You probably need to update the password in your `redis-server` config as well. Then restart redis and try the `bundle exec` command again`.

**Comment by thxmike** [comment]
I am getting the same error message. I went through the suggestions that were outlined but I still get the same message. Any assistance would be appreciated
bundler: failed to load command: thin (/home/ots/onetimesecret/vendor/bundle/ruby/1.9.1/bin/thin)
RuntimeError: ERR Client sent AUTH, but no password is set
  /home/ots/onetimesecret/vendor/bundle/ruby/1.9.1/gems/redis-2.2.2/lib/redis/client.rb:47:in `call'
  /home/ots/onetimesecret/vendor/bundle/ruby/1.9.1/gems/redis-2.2.2/lib/redis/client.rb:24:in `connect'
  /home/ots/onetimesecret/vendor/bundle/ruby/1.9.1/gems/redis-2.2.2/lib/redis/client.rb:247:in `ensure_connected'
  /home/ots/onetimesecret/vendor/bundle/ruby/1.9.1/gems/redis-2.2.2/lib/redis/client.rb:137:in `block in process'
  /home/ots/onetimesecret/vendor/bundle/ruby/1.9.1/gems/redis-2.2.2/lib/redis/client.rb:206:in `logging'
  /home/ots/onetimesecret/vendor/bundle/ruby/1.9.1/gems/redis-2.2.2/lib/redis/client.rb:136:in `process'
  /home/ots/onetimesecret/vendor/bundle/ruby/1.9.1/gems/redis-2.2.2/lib/redis/client.rb:46:in `call'
  /home/ots/onetimesecret/vendor/bundle/ruby/1.9.1/gems/redis-2.2.2/lib/redis.rb:273:in `block in ping'
  /home/ots/onetimesecret/vendor/bundle/ruby/1.9.1/gems/redis-2.2.2/lib/redis.rb:18:in `synchronize'
  /home/ots/onetimesecret/vendor/bundle/ruby/1.9.1/gems/redis-2.2.2/lib/redis.rb:272:in `ping'
  /home/ots/onetimesecret/lib/onetime.rb:73:in `block in load!'
  /home/ots/onetimesecret/lib/onetime.rb:73:in `times'
  /home/ots/onetimesecret/lib/onetime.rb:73:in `load!'
  config.ru:28:in `block in <main>'
  /home/ots/onetimesecret/vendor/bundle/ruby/1.9.1/gems/rack-1.4.5/lib/rack/builder.rb:51:in `instance_eval'
  /home/ots/onetimesecret/vendor/bundle/ruby/1.9.1/gems/rack-1.4.5/lib/rack/builder.rb:51:in `initialize'
  config.ru:1:in `new'
  config.ru:1:in `<main>'
  /home/ots/onetimesecret/vendor/bundle/ruby/1.9.1/gems/thin-1.5.0/lib/rack/adapter/loader.rb:33:in `eval'
  /home/ots/onetimesecret/vendor/bundle/ruby/1.9.1/gems/thin-1.5.0/lib/rack/adapter/loader.rb:33:in `load'
  /home/ots/onetimesecret/vendor/bundle/ruby/1.9.1/gems/thin-1.5.0/lib/thin/controllers/controller.rb:181:in `load_rackup_config'
  /home/ots/onetimesecret/vendor/bundle/ruby/1.9.1/gems/thin-1.5.0/lib/thin/controllers/controller.rb:71:in `start'
  /home/ots/onetimesecret/vendor/bundle/ruby/1.9.1/gems/thin-1.5.0/lib/thin/runner.rb:187:in `run_command'
  /home/ots/onetimesecret/vendor/bundle/ruby/1.9.1/gems/thin-1.5.0/lib/thin/runner.rb:152:in `run!'
  /home/ots/onetimesecret/vendor/bundle/ruby/1.9.1/gems/thin-1.5.0/bin/thin:6:in `<top (required)>'
  /home/ots/onetimesecret/vendor/bundle/ruby/1.9.1/bin/thin:23:in `load'
  /home/ots/onetimesecret/vendor/bundle/ruby/1.9.1/bin/thin:23:in `<top (required)>'

**Comment by thxmike** [comment]
I was able to correct this. It is the password in the redis string that needs to be updated in the config file for onetime password. This needs to match the requirepass <password> in the redis.conf file. "requirepass" needs to be uncommented as well.

**Comment by trazek** [comment]
Hello @thxmike, 

I tried your solution but still have the same error. Can you tell me which config files need to be updated with a password? I changed the redis.conf but do not see another to change.

Also, when I run the `redis-server` command, is it supposed to immediately terminate or should the instance of redis run, like if you just run `redis-server` without a config file as a param. 

Thanks

**Comment by trazek** [comment]
I was able to solve my issue by double checking (as stated) the password information matched in the config files. Something to mention, I had to wrap my password in quotes from the onetime config file:

``` requirepass "mypassword"```

Once I wrapped it in the quotes, it worked.

**Comment by emilyHere6** [comment]
@trazek What did the other file you had to edit look like? Was it the ect/config? What does that line look like for you?
