### ISSUE TITLE
0.17.1 container crash due to ostruct gem version lock

### ISSUE THREAD

**Issue by alemonmk** [onetimesecret/onetimesecret#626]
I updated the container to 0.17.1 and it crashes with this message:

```
/usr/local/bundle/gems/bundler-2.5.18/lib/bundler/runtime.rb:299:in `check_for_activated_spec!': You have already activated ostruct 0.6.0, but your Gemfile requires ostruct 0.5.5. Since ostruct is a default gem, you can either remove your dependency on it or try updating to a newer version of bundler that supports ostruct as a default gem. (Gem::LoadError)
	from /usr/local/bundle/gems/bundler-2.5.18/lib/bundler/runtime.rb:25:in `block in setup'
	from /usr/local/bundle/gems/bundler-2.5.18/lib/bundler/spec_set.rb:191:in `each'
	from /usr/local/bundle/gems/bundler-2.5.18/lib/bundler/spec_set.rb:191:in `each'
	from /usr/local/bundle/gems/bundler-2.5.18/lib/bundler/runtime.rb:24:in `map'
	from /usr/local/bundle/gems/bundler-2.5.18/lib/bundler/runtime.rb:24:in `setup'
	from /usr/local/bundle/gems/bundler-2.5.18/lib/bundler.rb:164:in `setup'
	from /usr/local/bundle/gems/bundler-2.5.18/lib/bundler/setup.rb:32:in `block in <top (required)>'
	from /usr/local/bundle/gems/bundler-2.5.18/lib/bundler/ui/shell.rb:159:in `with_level'
	from /usr/local/bundle/gems/bundler-2.5.18/lib/bundler/ui/shell.rb:111:in `silence'
	from /usr/local/bundle/gems/bundler-2.5.18/lib/bundler/setup.rb:32:in `<top (required)>'
	from <internal:/usr/local/lib/ruby/3.3.0/rubygems/core_ext/kernel_require.rb>:136:in `require'
	from <internal:/usr/local/lib/ruby/3.3.0/rubygems/core_ext/kernel_require.rb>:136:in `require'
	from /app/lib/onetime.rb:3:in `<top (required)>'
	from config.ru:22:in `require_relative'
	from config.ru:22:in `block in <main>'
	from /usr/local/bundle/gems/rack-2.2.9/lib/rack/builder.rb:125:in `instance_eval'
	from /usr/local/bundle/gems/rack-2.2.9/lib/rack/builder.rb:125:in `initialize'
	from config.ru:1:in `new'
	from config.ru:1:in `<main>'
	from /usr/local/bundle/gems/thin-1.8.2/lib/rack/adapter/loader.rb:33:in `eval'
	from /usr/local/bundle/gems/thin-1.8.2/lib/rack/adapter/loader.rb:33:in `load'
	from /usr/local/bundle/gems/thin-1.8.2/lib/thin/controllers/controller.rb:182:in `load_rackup_config'
	from /usr/local/bundle/gems/thin-1.8.2/lib/thin/controllers/controller.rb:72:in `start'
	from /usr/local/bundle/gems/thin-1.8.2/lib/thin/runner.rb:203:in `run_command'
	from /usr/local/bundle/gems/thin-1.8.2/lib/thin/runner.rb:159:in `run!'
	from /usr/local/bundle/gems/thin-1.8.2/bin/thin:6:in `<top (required)>'
	from /usr/local/bundle/bin/thin:25:in `load'
	from /usr/local/bundle/bin/thin:25:in `<main>'
```

Looked into Gemfile.lock:
https://github.com/onetimesecret/onetimesecret/blob/cc0776f6f3578b17fa63a1b3f36ba5eb383ce6f5/Gemfile.lock#L63

You specified `ruby:3.3-slim-bookworm` as the final base layer of the container, [ostruct is updated to 0.6.0 in Ruby 3.3](https://www.ruby-lang.org/en/news/2023/12/25/ruby-3-3-0-released/).

https://github.com/onetimesecret/onetimesecret/blob/cc0776f6f3578b17fa63a1b3f36ba5eb383ce6f5/Gemfile.lock#L223-L224

Did you forget updating your development environment? Or you may want to use 3.2 for base layer since the system requirement in README haven't include 3.3 yet.

**Comment by delano** [comment]
Hey thanks for making this report. 

> Did you forget updating your development environment? Or you may want to use 3.2 for base layer since the system requirement in README haven't include 3.3 yet.

Doh, I did mean for the Docker image to go to 3.3. After I noticed I did indeed forget to update my dev environment.

**Comment by delano** [comment]
@alemonmk Was there anything particular about how the container is running? I'm having trouble reproducing.

```bash
$ docker run -p 3000:3000 -d --name onetimesecret \
      -e REDIS_URL=$REDIS_URL \
      -e COLONEL=$COLONEL \
      -e HOST=$HOST \
      -e SSL=$SSL \
      -e RACK_ENV=$RACK_ENV \
      onetimesecret/onetimesecret:v0.17.1
Unable to find image 'onetimesecret/onetimesecret:v0.17.1' locally
v0.17.1: Pulling from onetimesecret/onetimesecret
Digest: sha256:24e25a7b4f24339d7c836927fac689f7e699051b68639bc43d24ed1716f442e9
Status: Downloaded newer image for onetimesecret/onetimesecret:v0.17.1
869dc04de6f87a9c9d8e8395c2b03fb09309137429c358abf7ca2a836597a8a4
```

Then the container logs:
```
2024-09-10 13:18:58 [Tue Sep 10 20:18:58 UTC 2024] INFO: Running entrypoint.sh...
2024-09-10 13:18:58 Skipping bundle install. Use BUNDLE_INSTALL=true to run it.
2024-09-10 13:19:08 10.10.10.1 - - [10/Sep/2024:20:19:08 +0000] "GET / HTTP/1.1" 200 23730 0.0379
2024-09-10 13:19:09 10.10.10.1 - - [10/Sep/2024:20:19:09 +0000] "GET / HTTP/1.1" 200 23730 0.0328
```

Running `bin/ots`
```bash
docker exec -it 869dc04de6f87a9c9d8e8395c2b03fb09309137429c358abf7ca2a836597a8a4 /bin/sh
# ruby -v
ruby 3.3.5 (2024-09-03 revision ef084cc8f4) +YJIT [aarch64-linux]
# bin/ots console
I(1725999596): Calling Onetime.boot!...
I(1725999596): ---  ONETIME cli v0.17.1 ()  ------------------------------
I(1725999596): Sysinfo: ruby-unix-linux-unknown (3.3.5) sync:false
I(1725999596): Config: /app/etc/config
I(1725999596): Redis (7.2.4): redis://host.docker.internal:6379/15
I(1725999596): Familia: 1.0.0-rc7
I(1725999596): Colonels: ["admin@example.com"]
I(1725999596): Authentication: {:enabled=>true, :signup=>true, :signin=>true, :autoverify=>false}
I(1725999596): Domains: {:enabled=>false, :default=>nil, :cluster=>{:type=>nil, :api_key=>nil, :cluster_ip=>"<CLUSTER_IP>", :cluster_name=>"<CLUSTER_NAME>", :vhost_target=>"<VHOST_TARGET>"}}
I(1725999596): Loaded locales: en, ar, bg, ca_ES, cn, cs, da_DK, de, el_GR, es, fr, fr_FR, he, hu, it_IT, nl, pl, pt_BR, pt_PT, ru, sl_SI, sv_SE, tr, uk, vi
I(1725999596): Limits: {:create_secret=>1000, :create_account=>10, :update_account=>10, :email_recipient=>50, :send_feedback=>10, :authenticate_session=>5, :homepage=>1000, :dashboard=>1000, :failed_passphrase=>5, :show_metadata=>1000, :show_secret=>1000, :burn_secret=>1000, :destroy_account=>2, :forgot_password_request=>2, :forgot_password_reset=>3, :generate_apikey=>10, :add_domain=>30, :remove_domain=>30, :list_domains=>100, :get_domain=>100, :verify_domain=>25}

Onetime console loaded (additional settings applied: true).
History not saved. Use 'exit' to quit.

onetime> OpenStruct::VERSION
⮑  "0.5.5"
onetime> Bundler::VERSION
⮑  "2.5.18"
onetime> 
onetime> 
^C
onetime> exit
#     
```

**Comment by alemonmk** [comment]
Yeah it seem to run fine when I launch the container manually too.

Normally I run it with Nomad with image hosted on ghcr.io:
```
    task "onetimesecret" {
      driver = "docker"

      config {
        image        = "ghcr.io/onetimesecret/onetimesecret:v0.17.1"
        args         = ["thin", "-R", "config.ru", "-p", "${NOMAD_PORT_http}", "start"]
        cap_drop     = ["all"]
        ports        = ["http"]
        network_mode = "host"
        mount {
          type     = "bind"
          target   = "/app/etc/config"
          source   = "secrets/config"
          readonly = true
        }
      }
```
However aside from the crash message above I got nothing.

BTW I don't know what have Familia done but now I need to take out -@dangerous from redis ACL...

**Comment by delano** [comment]
Thanks for the info. 

I'll need to run some tests to see exactly which `@dangerous` category commands exactly are being used but it's probably `keys` or another of the ones that can be very slow.

I'd usually take a closer look and have a more specific answer but we're dealing with a DDoS on onetimesecret.com this week.

**Comment by delano** [comment]
The Gemfile.lock is updated to ostruct 0.6.0 in release v0.17.2.

**Comment by alemonmk** [comment]
Hey @delano, it seems there's a [critical commit](https://github.com/onetimesecret/onetimesecret/commit/dc03961879b3f0efb209b3b4b6083e0940277a8c) that [was not included](https://github.com/onetimesecret/onetimesecret/compare/v0.17.3...develop) in the latest release tag, without it Github action docker image push keeps failing.

**Comment by delano** [comment]
Oh weird that those failures don't show up on the main Actions screen. 
<img width="640" alt="Screenshot 2024-09-17 at 11 24 58" src="https://github.com/user-attachments/assets/741173ad-1998-47af-b6dd-1377e47f2ae4">
<img width="640" alt="Screenshot 2024-09-17 at 11 24 09" src="https://github.com/user-attachments/assets/ffa28e81-b61b-4a42-90ba-d630228f250d">


Thanks for pinging me. I'll push a fix now. Looks like I also forgot to increment the patch version.

**Comment by alemonmk** [comment]
Image push happens with v* tags, rel/0.17 tag has that commit so they are fine.

Tested new container and they are working fine, thank you.
